### PR TITLE
Fix election RBAC YAML

### PR DESCRIPTION
**Pull request by keeganwitt**

### CODE REVIEW

**Comment by evan2645** [comment]
Hey @faisal-memon would you mind having a look at this?

**Comment by faisal-memon** [comment]
Looks ok to me. I would suggest enabling leader election by default by adding `leader_election=true` to the config here: https://github.com/spiffe/spire/blob/main/support/k8s/k8s-workload-registrar/mode-crd/config/spire-server-registrar.yaml#L153-L163

**Comment by faisal-memon** [comment]
can you also update the readme to deploy the roles.yaml? https://github.com/keeganwitt/spire/blob/election_roles/support/k8s/k8s-workload-registrar/mode-crd/README.md?plain=1#L64-L66

**Comment by faisal-memon** [comment]
One last thing, can you add the `-f https://raw.githubusercontent.com/spiffe/spire/main/support/k8s/k8s-workload-registrar/mode-crd/config/roles.yaml \` here: https://github.com/spiffe/spire/pull/3617/files#diff-6efa9a0191dcc6fa8c00d35403d17808aeacc182a41fbbaa35ae2ba1612d23adL263

**Comment by keeganwitt** [comment]
> One last thing, can you add the `-f https://raw.githubusercontent.com/spiffe/spire/main/support/k8s/k8s-workload-registrar/mode-crd/config/roles.yaml \` here: https://github.com/spiffe/spire/pull/3617/files#diff-6efa9a0191dcc6fa8c00d35403d17808aeacc182a41fbbaa35ae2ba1612d23adL263

I don't understand what's being requested here. The README already has the `-f` in it.

**Comment by faisal-memon** [comment]
> I don't understand what's being requested here. The README already has the `-f` in it.

Sorry, line 263 under the `Deleting the Quick Start` section to remove the roles when deleting.

**Comment by keeganwitt** [comment]
> > I don't understand what's being requested here. The README already has the `-f` in it.
> 
> Sorry, line 263 under the `Deleting the Quick Start` section to remove the roles when deleting.

Ah, OK. Added.

**Review by azdagron — APPROVED** [review]
Thanks, @keeganwitt! Would you mind resolving the merge conflict? We're good to merge after that.

**Comment by keeganwitt** [comment]
> Thanks, @keeganwitt! Would you mind resolving the merge conflict? We're good to merge after that.

Done.

**Review by azdagron — APPROVED** [review]

**Pull request merged**
