### PR TITLE
Fix for health checks race at startup

### LINKED ISSUE #2063: Health checks errors may be shown at startup
There could be a race at startup time where the health checks can be executed before the server is serving. In that case, throwing an error is inappropriate and could be confusing.
This can happen both in SPIRE Server and SPIRE Agent.

* **Version**: 277aabfa24c2e222d280f0a8a17cc0cb234acee4

### PR DESCRIPTION
**Pull request by amartinezfayo**
Wait for the availability of the Agent API socket and the Server API socket before starting the health checks

Fixes #2063.

### CODE REVIEW

**Review by azdagron — APPROVED** [review]
\o/ Thanks for this @amartinezfayo. I think there is a little bit of a leaky abstraction here, since the agent and server packages now have some knowledge of how the health checks are constructed (i.e. that they hit the API), but I think this is ok for now.

**Comment by amartinezfayo** [comment]
>I think there is a little bit of a leaky abstraction here, since the agent and server packages now have some knowledge of how the health checks are constructed (i.e. that they hit the API), but I think this is ok for now.

The agent and server packages already know the specifics of the health checks since they have the implementation of the Status() function. I'm not sure if maybe I'm missing something?

**Comment by azdagron** [comment]
Oh duh. You are right. For some reason I thought that functionality was tucked elsewhere. This is fine.

Thanks again!

**Comment by azdagron** [comment]
I do imagine at some point (like when the http and grpc health handling becomes shared, we'll remove the details of the health concerns from the pkg/agent and pkg/server packages. But that can come later.

**Pull request merged**
