### PR TITLE
Check in the AWS IID node attestor

### PR DESCRIPTION
**Pull request by evan2645**
This commit checks in the node attestor work done by @juturnas in github.com/spiffe/aws-iid-attestor

It has essentially been copy/pasted in the interest of time, applying only the necessary changes requred for a built-in plugin (hence the absence of tests).

The plugin name for this builtin is `aws_iid`, as opposed to the out-of-process plugin name of `aws_iid_attestor`... Besides being more idiomatic, the new name should prevent collisions with the previous plugin should it be loaded on top of an updated codebase. Though the code is identical, I have not performed an end-to-end test due to lack of AWS creds - it would be great if @walmav or @drrt could give this a quick whirl to ensure everything is good.

Once #369 is merged, I will either update this PR or send a new PR to add documentation for this addition.

@juturnas: I tried my hardest to commit an author line that linked to your GH profile, though failed on all attempts :(. Sorry about that... happy to update it if you can provide a "working" author line. Thanks for your work on this!

### CODE REVIEW

**Comment by ajessup** [comment]
Excited to see this merged into the main repo

**Comment by evan2645** [comment]
Update: pending CLA completion from Blend

@jondb @juturnas please ping back when complete, and thanks again for this contrib :)

**Comment by evan2645** [comment]
Per @suniljames, we will go ahead and merge this since we expect Blend to sign a CLA in the near future. This can be easily reverted if need be.

**Comment by evan2645** [comment]
@walmav for a quick functional test ❤️

**Comment by walmav** [comment]
verified that it works as expected

**Pull request merged**
