### PR TITLE
Add database migration dry run feature

### PR DESCRIPTION
**Pull request by mweissbacher**
**Affected functionality**
This PR adds a dry run feature for migrations. It will write the migration procedure per migration level to a file and exit. The migrations are performed against the database - transactions are opened and rolled back.

**Description of change**
Two new configuration options: `migration_dry_run` and `dry_run_file_name`.

When starting a migration dry run with the database at level 6 where the code is at level 10, this is the output of spire server:

```
...
INFO[0000] Done printing migration to 7. Rolling back.   subsystem_name=built-in_plugin.sql
INFO[0000] Done printing migration to 8. Rolling back.   subsystem_name=built-in_plugin.sql
INFO[0000] Done printing migration to 9. Rolling back.   subsystem_name=built-in_plugin.sql
INFO[0000] Done printing migration to 10. Rolling back.  subsystem_name=built-in_plugin.sql
INFO[0000] Migrations written to file migration.sql      subsystem_name=built-in_plugin.sql

Process finished with exit code 0
```

The output file looks as follows for sqlite:

```
-- Migration from v6 to v7
ALTER TABLE "registered_entries" ADD "expiry" bigint;
UPDATE "migrations" SET "updated_at" = '2019-09-09 11:17:04', "version" = 7  ;
-- Migration from v7 to v8
ALTER TABLE "registered_entries" ADD "expiry" bigint;
CREATE TABLE "dns_names" ("id" integer primary key autoincrement,"created_at" datetime,"updated_at" datetime,"registered_entry_id" integer,"value" varchar(255) );
CREATE UNIQUE INDEX idx_dns_entry ON "dns_names"(registered_entry_id, "value") ;
UPDATE "migrations" SET "updated_at" = '2019-09-09 11:17:04', "version" = 8  ;
-- Migration from v8 to v9
ALTER TABLE "registered_entries" ADD "expiry" bigint;
CREATE INDEX idx_registered_entries_spiffe_id ON "registered_entries"(spiffe_id) ;
CREATE INDEX idx_registered_entries_parent_id ON "registered_entries"(parent_id) ;
CREATE INDEX idx_selectors_type_value ON "selectors"("type", "value") ;
UPDATE "migrations" SET "updated_at" = '2019-09-09 11:17:04', "version" = 9  ;
-- Migration from v9 to v10
ALTER TABLE "registered_entries" ADD "expiry" bigint;
CREATE INDEX idx_registered_entries_spiffe_id ON "registered_entries"(spiffe_id) ;
CREATE INDEX idx_registered_entries_parent_id ON "registered_entries"(parent_id) ;
CREATE INDEX idx_registered_entries_expiry ON "registered_entries"("expiry") ;
UPDATE "migrations" SET "updated_at" = '2019-09-09 11:17:04', "version" = 10  ;
```

### CODE REVIEW

**Comment by azdagron** [comment]
Hi @mweissbacher! @evan2645  and I discussed this a bit offline and he mentioned we should get #1089 in first. While we're working on that though, I had a few questions.

Where do you envision this being run? How do you plan on retrieving the results? Is this meant to just be run manually from a developer/ops machine? If so, will you have your production SPIRE server configuration available? What other side effects might happen by loading up all of SPIRE server just to perform this small task?

Ideally, all things being equal, we think what might make the most sense is:
1) Exporting the functionality from the `github.com/spiffe/spire/pkg/server/plugin/datastore/sql` package.
2) Consuming that method from a small, scoped CLI utility (perhaps living under `github.com/spiffe/spire/support somwehere)

That would make it easier to run, be less risky, and removes some of the concerns from the current PR (like calling os.Exit from the plugin). Thoughts?

Also, I think there is some opportunity to DRY this up instead of forking `migrateDB()` completely. As is, we'd have to update both spots when adding a migration. I'm allergic to DRY for DRY's sake, but I think it could be done cleanly...

**Comment by mweissbacher** [comment]
Hi @azdagron ! The way I'd like to use such a tool is by running it either against a staging server that mirrors the production environment or against production directly. This would be run manually, the output can then be either run directly against the database or plugged into a database migration tool like gh-ost.

You're right - exporting parts of the SQL package and moving to standalone tool would make this cleaner. Let's wait until #1089 is merged and I'll pick this up then.

**Comment by azdagron** [comment]
Heads up @mweissbacher, #1089 has been merged.

**Comment by mweissbacher** [comment]
Thanks @azdagron !

**Comment by evan2645** [comment]
@mweissbacher I assume you're still planning on picking this back up? Was just looking over the diff, seems like most of it won't be applicable if we instead export some functions and ship a helper utility. How would you like to proceed? Close this PR and open a new one? Create an issue that captures this conversation...? Or something else? I ask only because this one is becoming a little stale.

**Comment by mweissbacher** [comment]
Hey, I started working on moving this to a helper utility but didn't wrap it up, other work came in the way. New PR would be cleaner, I'll close this and open an issue for better tracking.

**Pull request closed without merging**
