### PR TITLE
Centralize Tool Version Management with .project-versions

### PR DESCRIPTION
**Pull request by maxlambrecht**
**Pull Request check list**

- [X] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [X] Documentation updated?

**Affected functionality**

**Description of change**

This PR introduces a `.project-versions` file to centralize version information for various tools used in the `Makefile`. It also updates the project documentation to include a section about the `.project-versions` file.

**Which issue this PR fixes**

### CODE REVIEW

**Comment by azdagron** [comment]
This seems fine. Thanks @maxlambrecht. My only suggestion is that maybe we name the file ".tool-versions"...

**Comment by maxlambrecht** [comment]
> This seems fine. Thanks @maxlambrecht. My only suggestion is that maybe we name the file ".tool-versions"...

I initially chose `.tool-versions`. However, I discovered it is currently listed in the `.gitignore` file as a result of #3661.

**Comment by azdagron** [comment]
How about `.spire-tool-versions`

**Comment by maxlambrecht** [comment]
> How about `.spire-tool-versions`

Sounds good!

**Review by azdagron — APPROVED** [review]

**Pull request merged**
