### PR TITLE
Fix OIDC healthcheck to work with k8s healthprobes

### LINKED ISSUE #3572: oidc-discovery-provider healthcheck endpoint does not work
* **Version**: 1.5.0
* **Platform**: EKS 1.23
* **Subsystem**: spire-oidc-provider

Using the scratch images on `ghcr.io` I can't use the following readiness probe anymore.

```yaml
readinessProbe:
  exec:
    command: ["/bin/ps", "aux", "|", "grep", "oidc-discovery-provider -config /run/spire/oidc/config/oidc-discovery-provider.conf"]
```

However the healthcheck endpoint also doesn't work due to the fact it only listens on localhost.

https://github.com/spiffe/spire/blob/main/support/oidc-discovery-provider/main.go#L103

See here my k8s httpGet probes.

```yaml
          readinessProbe:
            httpGet:
              path: /ready
              port: 8008
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /live
              port: 8008
            initialDelaySeconds: 5
            periodSeconds: 5
```

These fail with the following message:

```shell
Readiness probe failed: Get "http://10.0.12.97:8008/ready": dial tcp 10.0.12.97:8008: connect: connection refused
Liveness probe failed: Get "http://10.0.12.97:8008/live": dial tcp 10.0.12.97:8008: connect: connection refused
```

As you can see these probes do not use localhost, but the pod IP.

### PR DESCRIPTION
**Pull request by marcofranssen**
**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [x] Proper tests/regressions included?
- [x] Documentation updated?

**Affected functionality**

oidc-provider healthcheck endpoint

**Description of change**

Allows the healthcheck to be called by ip address as well, so it works for kubernetes healthprobes.

**Which issue this PR fixes**

fixes #3572

### CODE REVIEW

**Review by MarcosDY — APPROVED** [review]

**Comment by marcofranssen** [comment]
@MarcosDY @azdagron According to the changelog of releases this hotfix has not been released yet.

Can we get a hotfix release for this? `1.5.2`?

**Comment by azdagron** [comment]
We don't typically do one-off patch releases for bug fixes unless it is a regression. In this instance, the health checks never worked on K8s to begin with. Are we overlooking a reason that this should be treated more urgently?

In any case, I'll bring it up in today's contributor sync meeting.

**Comment by marcofranssen** [comment]
Only reason is that I want to enable the healthchecks again on the helm-chart. Since we moved to use the scratch images I can't use the old `ps aux` approach anymore.

https://github.com/philips-labs/helm-charts/blob/main/charts/spire/templates/oidc-deployment.yaml#L58-L70

**Comment by azdagron** [comment]
You can also test using the nightly images if that helps.

**Pull request merged**
