### PR TITLE
Determine envoy release for integration test

### PR DESCRIPTION
**Pull request by azdagron**
The latest tag for envoyproxy/envoy-alpine isn't available. Instead of
relying on the latest tag, use github to determine the latest release
for envoyproxy/envoy.

### CODE REVIEW

**Comment by evan2645** [comment]
Is there an upstream issue? Is `latest` tag being discontinued, or do we expect it to come back?

Does anyone at Envoy know they cut w/o the tag? 😆

**Comment by azdagron** [comment]
Whelp. https://github.com/envoyproxy/envoy/issues/10738.

**Comment by azdagron** [comment]
TL;DR tag removal is intentional.

**Comment by evan2645** [comment]
It would be useful to see Envoy issues/discussion around the reasoning for removal.

Is this change still the fix that you'd propose?

**Comment by azdagron** [comment]
This change hits the latest release page on github, and then grabs the version off of the redirect URL. There might be alternatives, like hitting the github api instead, but that requires interpreting JSON.

**Pull request merged**
