### PR TITLE
Update Azure SDK usage to use newer packages

### PR DESCRIPTION
**Pull request by rturner3**
The Azure SDK has been refactored to use Go submodules. Take direct dependencies on only the modules we actually use.

The new submodules also change the shape of the models and client APIs.

### CODE REVIEW

**Comment by rturner3** [comment]
Keeping in draft state until I've had a chance to test this in Azure.

**Review by azdagron — COMMENTED** [review]
Looks good in general. Anxious to see test outcomes.

**Review by azdagron — DISMISSED** [review]

**Comment by MarcosDY** [comment]
I tested it on azure using a VM and all works as before, I was able to attest server and agent, and use node resolver to get selectors and create an alias

**Comment by rturner3** [comment]
> I tested it on azure using a VM and all works as before, I was able to attest server and agent, and use node resolver to get selectors and create an alias

Thank you for giving this a go, @MarcosDY ! 🙏 

Moving this from draft status to ready to review.

**Comment by rturner3** [comment]
Sorry for the force push, rebased when I should have merged...

**Comment by rturner3** [comment]
go.mod merge didn't go as expected, fixing that up now.

**Review by azdagron — APPROVED** [review]
\o/

**Pull request merged**
