### PR TITLE
tools/plugintest: Add tool for testing workload attestation plugins

### PR DESCRIPTION
**Pull request by APTy**
**Pull Request check list**

- [ ] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**
This adds a `plugintest` tool that allows users to validate the behavior of their workload attestation plugins. It takes the name of a binary and a pid, and runs workload attestation against it. The `unixworkloadattestor` is provided as an example of how to test a plugin.

This provides a simpler validation path for third party plugin builders, since they can develop a plugin independent of a running SPIRE agent.

**Description of change**
```
$ go build -o plugintest ./tools/plugintest/main.go
$ go build -o unixworkloadattestor ./tools/plugintest/unixworkloadattestor/main.go

$ ./plugintest
Usage: ./plugintest <plugin_binary> <pid>

$ ./plugintest ./unixworkloadattestor $$
Workload Attestation Results (Pid 3476)
  unix:uid:1001
  unix:user:apty
  unix:gid:1001
  unix:group:apty

$ ./plugintest ./unixworkloadattestor 1
Workload Attestation Results (Pid 1)
  unix:uid:0
  unix:user:root
  unix:gid:0
  unix:group:root
```

**TODO**
How do we want to integrate this with the project better? i.e. part of the make process, etc.

### CODE REVIEW

**Comment by APTy** [comment]
also let me know if it doesn't feel like this "fits" in the spire repo, I can always put it elsewhere, just felt that these types of tools that work out the APIs of plugins will be useful for third party developers

**Comment by evan2645** [comment]
Do we want to hook this into the test suite, or is it OK to merge as is?

**Comment by azdagron** [comment]
I'm ok merging as is. We can do additional work later to integrate it. The workload attestor interface isn't likely to change anytime soon so I'm not worried about it getting stale. @APTy, thoughts?

**Comment by APTy** [comment]
Yeah that sounds fine for now. Perhaps on our next pass at workload attestation plugins we can look at creating a tighter integration, but may not be totally necessary

**Pull request merged**
