### PR TITLE
Pin GH actions

### PR DESCRIPTION
**Pull request by marcofranssen**
Dependabot is also capable of pinning to future tag releases
and will maintain the comment that describes the shasum.

https://github.com/dependabot/dependabot-core/issues/4691

**This will ensure you always use the action at the commit when a version bump takes place. Even if someone overwrites the tag with a new (malicious) tag.**

**Pull Request check list**

- [ ] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

**Description of change**

**Which issue this PR fixes**

### CODE REVIEW

**Comment by evan2645** [comment]
Thanks for opening this @marcofranssen ❤️ 

I opened [an issue](https://github.com/spiffe/spire/issues/3729) related to this, but it definitely seems like a welcome change. We discussed this on a previous contributor call, and one thing we wondered is if it is possible to define these versions and hashes at the top of each worfklow, as a set of variables ... there are many places that we use the same action in each workflow and consolidating the versions might make it easier to manage ... but only if it works (😂) and if dependabot would still update them (unsure...).

Let me know what you think .. thanks again!

**Comment by marcofranssen** [comment]
Dependabot will manage it for you. It only works if it is inline. As soon it moves to environment variable you are on your own. Every time a new version is found dependabot will open a pr that updates the comment and shasum. Then it is up to reviewer to check release notes in pr description, check that build succeeds etc. 

You could even make a workflow that auto approves dependabot PRs if it meets certain criteria.

**Comment by evan2645** [comment]
Ok .. I think this is ready to go, but there are a couple conflicts that look related to recent code signing changes. Mind having a look and then we can get this merged?

**Comment by marcofranssen** [comment]
Sure will do tomorrow.

**Comment by evan2645** [comment]
Hey @marcofranssen , gentle ping on this, it's ready to go aside from the conflicts

**Comment by marcofranssen** [comment]
Let me check this conflicts first thing tomorrow

**Comment by evan2645** [comment]
Thank you!! ❤️

**Review by evan2645 — APPROVED** [review]

**Pull request merged**
