### PR TITLE
Bump max received msg size for Agent fetchEntries to 32MB

### PR DESCRIPTION
**Pull request by amoore877**
Signed-off-by: amoore877 <andrew.s.moore@uber.com>

**Pull Request check list**

- [X] Commit conforms to CONTRIBUTING.md?
- [X] Proper tests/regressions included?
- [N/A] Documentation updated?

**Affected functionality**
Agent grpc max received message size over connections with Server to get authorized entries.

**Description of change**
The default max size is 4MB. Per [investigation](https://github.com/spiffe/spire/issues/2675#issuecomment-1035237101) and local reproduction of results this is about 17k registration entries.

Set the new maximum to 32MB.

Using the same quick check script as above, this bumps the limit to about 135.5k entries, which is theorized to be more than sufficient for operators while #2675 and #2845 are being addressed with long-term solutions for reduction of overhead + batching and/or changing the API to a streaming RPC / pagination.

This high limit was chosen to ensure that we do not need to patch this again in the meantime.

Anticipate that any operators who would regress from this change are either:
- already in a broken state due Agent being unable to sync registrations from Server. Unbreaking this portion of their ecosystem either fixes their ecosystem or reveals the next issue with their configuration, like not properly setting resource configs for the Agent.
- created a situation that would normally prevent Agent syncing but instead increases Agent resource usage.

Anticipate that removal of this patch later when we have a true solution to the problem in place will have no regressive effect, as the long-term solution should lower or eliminate chances of exceeding max message sizes.

**Which issue this PR fixes**
Does not provide a permanent fix to any PR.

### CODE REVIEW

**Comment by amoore877** [comment]
```
level=warning msg="[linters context] bodyclose is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649."
level=warning msg="[linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649."
level=warning msg="[linters context] unparam is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649."
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
make: *** [Makefile:426: lint-code] Error 4
```
for [windows lint](https://github.com/spiffe/spire/runs/7675753545?check_suite_focus=true)?

is main missing something for windows-specific files?

**Comment by azdagron** [comment]
Thanks for opening this, @amoore877. We're a little concerned about bumping this number globally. If we do bump it, it should probably just be for the GetAuthorizedEntries call instead of all RPCs between the agent and server.

Reducing the limit in the future might be hard if we're not careful. It would be awful to brick a deployment on upgrade because we dropped the limit.

This PR spawned a conversation on more sustainable alternatives that aren't just a stopgap. We're feeling those alternatives out and will report back.

**Comment by amoore877** [comment]
> Reducing the limit in the future might be hard if we're not careful. It would be awful to brick a deployment on upgrade because we dropped the limit.

Agreed, hence some of the analysis in the PR summary of presumed cases this change would affect. I am not entirely convinced that someone would encounter such problems while also properly maintaining their ecosystem. One would need to grant SPIRE Agent 10s of GB in RAM to maintain this many SVIDs in an Agent (admittedly a lot less once #3181 is merged), and it's not good practice to have such an Agent be a resource hog.

To me, an upgrade would be blocked on dropping the limit if both 1) the drop did not also include a long-term solution to the problem and either 2A) the ecosystem was not being tidied up via pruning or deletions of entries or 2B) the consumer legitimately depended on this stopgap from the start, so of course it broke them.

However, see below.

> We're a little concerned about bumping this number globally. If we do bump it, it should probably just be for the GetAuthorizedEntries call instead of all RPCs between the agent and server.
> ...
> This PR spawned a conversation on more sustainable alternatives that aren't just a stopgap. We're feeling those alternatives out and will report back.

Thanks. In the meantime, I've updated to just touch the one API.

If the other solutions are not as potentially long-running multi-version efforts as initially thought, that would be the best path forward :)

**Comment by azdagron** [comment]
Hi @amoore877, after some discussion I think we're either going to introduce a server-streaming RPC to facilitate streaming the response back, or design and implement something that also reduces the network traffic. We're going to do a spike on the latter to see where we can get. If it looks like it will be a long time out, we'll go for the former, which there is already some implementation of from a recent spike (just missing some tests).

**Comment by keeganwitt** [comment]
What was the spike? Has it been merged already?

**Comment by azdagron** [comment]
https://github.com/spiffe/spire/issues/3496. It has not been merged. The issue provides a link to some implementation. We might get this in for 1.5.2 behind a developer feature flag.

**Pull request closed without merging**
