### PR TITLE
spire-server fix run_posix_test case

### PR DESCRIPTION
**Pull request by zmt**
- [x] Commit conforms to CONTRIBUTING.md?

**Affected functionality**
Change expected response code for a single test case in spire-server `run_posix_test.go` (`TestCommand_Run/create_data_dir_when_config_is_loaded_and_server_stops`).

**Description of change**
I noticed a single consistently failing test case on main in my linux dev environment. This change passes ci today. I bisected my local failure to the commit associated with #3505.

I'm not sure why this test case would not fail elsewhere or otherwise escaped detection by ci. It's possible that [killServerOnStart](https://github.com/spiffe/spire/blob/main/cmd/spire-server/cli/run/run_posix_test.go#L188) could be flaky depending on system capabilities, but that's just a guess.

### CODE REVIEW

**Comment by amartinezfayo** [comment]
@guilhermocc could you take a look?

**Comment by guilhermocc** [comment]
> @guilhermocc could you take a look?

Yes!

**Comment by evan2645** [comment]
Closing out in favor of https://github.com/spiffe/spire/pull/4250

**Comment by evan2645** [comment]
Thank you @zmt !!

**Pull request closed without merging**
