### PR TITLE
[spire-server] use DefaultServeMux for profiling

### PR DESCRIPTION
**Pull request by ZymoticB**
`net/http/pprof.Index` only supports named profiles, which does not
include `profile`. https://golang.org/src/net/http/pprof/pprof.go#L229

However, as an import side effect, `net/http/pprof` does register
[Profile](https://golang.org/src/net/http/pprof/pprof.go#L116) on
`net/http.DefaultServerMux`. This is the handler that `go tool pprof`
uses so ensure it is supported is pretty important.

### CODE REVIEW

**Comment by ZymoticB** [comment]
Agreed that DefaultServeMux isn't great, I'm not aware of any other way to enable `go tool pprof`.

**Comment by azdagron** [comment]
In previous projects, I've just copied the `init()` method from `net/http/pprof` and used it to set up our own handler. The handlers don't change frequently so it hasn't been very onerous to update it when a new go release adds a new one.

**Comment by ZymoticB** [comment]
Fair enough. Also just noticed that travis is failing, will try to get to that later today.

**Comment by azdagron** [comment]
It's a transient failure due to something outside of our control. I've restarted the failed job.

**Pull request merged**
