### PR TITLE
Fix Docker setup instructions

### PR DESCRIPTION
**Pull request by glaucimar**
Remove mention to "make container" as the target does not exist in make file. Replaced this with instruction to run "make images" to build SPIRE docker images.

**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [x] Documentation updated?

**Affected functionality**

**Description of change**

**Which issue this PR fixes**

### CODE REVIEW

**Review by evan2645 — APPROVED** [review]
Thank you very much @glaucimar!

**Comment by azdagron** [comment]
I'm wondering if we should remove most of that section, except the link to setting up Docker itself. The SPIRE docker images built by `make images` aren't used in the rest of the 101 and it's confusing on why you'd build them but then not use them.

**Comment by glaucimar** [comment]
> I'm wondering if we should remove most of that section, except the link to setting up Docker itself. The SPIRE docker images built by `make images` aren't used in the rest of the 101 and it's confusing on why you'd build them but then not use them.

I was wondering the same thing.. the only reason I took this path was to validate docker installation and setup.

**Comment by evan2645** [comment]
I think the entire file could use some love. For instance, it probably makes sense for us to reference the "full" config examples, etc. The diagram is outdated as well

I don't see it linked from the readme. There is a link from the `using_spire.md` doc but I don't see a link to that from the readme either.

If we want to remove the `Docker Setup` section entirely, I think that's fine. Looking at the commit history, I can see that [this step used to be required](https://github.com/spiffe/spire/blob/eb1c3ed0dd571c6318887361fc286e45c4d07756/doc/SPIRE101.md), but changes over the years orphaned it.

**Comment by glaucimar** [comment]
> I think the entire file could use some love. For instance, it probably makes sense for us to reference the "full" config examples, etc. The diagram is outdated as well
> 
> I don't see it linked from the readme. There is a link from the `using_spire.md` doc but I don't see a link to that from the readme either.
> 
> If we want to remove the `Docker Setup` section entirely, I think that's fine. Looking at the commit history, I can see that [this step used to be required](https://github.com/spiffe/spire/blob/eb1c3ed0dd571c6318887361fc286e45c4d07756/doc/SPIRE101.md), but changes over the years orphaned it.

ok.. I am willing to work out the document as I want to run SPIRE server and agent in Docker. I will re-submit this patch with only the change to remove Docker setup session and then, when I can go through the rest of the page, I submit another PR for the rest. This will probably take some days as I am on 101, right? So, still learning to fix this one. ;)

**Review by azdagron — APPROVED** [review]

**Pull request merged**
