### PR TITLE
update crio regex for intra-pod workload attestation

### LINKED ISSUE #4917: SPIRE agent cannot verify identity within own pod
* **Version**: `1.8.5` / `latest`
* **Platform**: `linux/amd64`
* **Subsystem**: agent

The SPIRE agent cannot verify the identity of other processes running in the same pod. This is because of the `cgroup` for the PID the agent can see for intra-pod containers does not contain the PodUID.

## Steps to reproduce

I discovered this while trying to secure the `spire-agent` telemetry endpoint behind an Envoy deployed as a sidecar in the same pod, using the agent for SDS. However, there is a much easier way to reproduce this:

1. Follow the [Quickstart for Kubernetes](https://spiffe.io/docs/latest/try/getting-started-k8s/) example up to "Configure and deploy the SPIRE Agent".

2. Replace `agent-daemonset.yaml` with the following and apply:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spire-agent
  namespace: spire
  labels:
    app: spire-agent
spec:
  selector:
    matchLabels:
      app: spire-agent
  template:
    metadata:
      namespace: spire
      labels:
        app: spire-agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: spire-agent
      initContainers:
        - name: init
          # This is a small image with wait-for-it, choose whatever image
          # you prefer that waits for a service to be up. This image is built
          # from https://github.com/lqhl/wait-for-it
          image: cgr.dev/chainguard/wait-for-it
          args: ["-t", "30", "spire-server:8081"]
      containers:
        - name: client
          image: ghcr.io/spiffe/spire-agent:1.5.1
          command: ["/opt/spire/bin/spire-agent"]
          args: [ "api", "watch",  "-socketPath", "/run/spire/sockets/agent.sock" ]
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
        - name: spire-agent
          #image: ghcr.io/spiffe/spire-agent:1.5.1
          image: critterjohnson/spire-agent:latest
          args: ["-config", "/run/spire/config/agent.conf"]
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-bundle
              mountPath: /run/spire/bundle
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: false
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: spire-config
          configMap:
            name: spire-agent
        - name: spire-bundle
          configMap:
            name: spire-bundle
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
```

The only difference this has from the regular Daemonset is that the agent container from the `client` Deployment was copied in.

3. Register the node as normal, but instead of the provided command for the workload, run

```
kubectl exec -n spire spire-server-0 -- \
    /opt/spire/bin/spire-server entry create \
    -spiffeID spiffe://example.org/ns/default/sa/default \
    -parentID spiffe://example.org/ns/spire/sa/spire-agent \
    -selector k8s:ns:spire \
    -selector k8s:sa:spire-agent
```

4. Check the `client` container logs: `kubectl logs -n spire spire-agent-4tnlr -c client` (replacing `4tnlr` with the uid given to the pod). You'll see a ton of `no identity issued` logs (which also appear in the agent, of course).

To confirm that what I listed is indeed the issue, I forked the repo and added a regex for the `cgroup` without pod UID (which the logic was already there to support, just not the correct regex prefix of `cri-`). The commented out line in the above Daemonset that changes the agent image points to my forked build. If you re-apply the manifests with that image, the client will receive its SVID.

### PR DESCRIPTION
**Pull request by critterjohnson**
**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [x] Proper tests/regressions included?
- [x] Documentation updated?

**Affected functionality**

This PR updates the `cgroup` regex for workloads in the same pod as the agent. It affects the `k8s` WorkloadAttestor.

**Description of change**

This PR updates the `cgroup` regex for workloads in the same pod as the agent. Without this, any containers in the the agent's pod cannot verify with the agent.

**Which issue this PR fixes**

fixes #4917

### CODE REVIEW

**Comment by evan2645** [comment]
Thank you very much for sending this @critterjohnson - we assigned @azdagron who is doing some related work right now. He should touch back here in the next week or two with an update. Thanks for your patience

**Comment by critterjohnson** [comment]
@azdagron any updates here? I saw y'all moved the milestone for the cgroups issue to 1.9.3. Of course this is part of that larger issue, but this is a good band-aid for this use case.

**Review by azdagron — APPROVED** [review]
Thanks, @critterjohnson. This looks good and I'm glad it solves your edge case.

The work to more fully support cgroups v2 will almost completely replace our algorithm used to determine the container ID. When I have a PR ready, I'd love for you to give it a go in your environment.

**Comment by azdagron** [comment]
Hmm, looks like this breaks existing unit tests.

> 2024/04/03 15:20:10 More than one regex matches for cgroup /kubepods-besteffort-pod72f7f152_440c_66ac_9084_e0fc1d8a910c.slice:cri-containerd:b2a102854b4969b2ce98dc329c86b4fb2b06e4ad2cc8da9d8a7578c9cd2004a2

There is a check that a given cgroup only matches one regex. Matching more than one regex isn't actually problematic unless the match would yield a different set of results, but the code isn't that smart (yet).

Since both this PR and the cgroups v2 support work that is under way are both slated for 1.9.3, one option is to just wait to see if that cgroups v2 work covers this case sufficiently. Otherwise, we'll need to change the code to relax a little like i described above.

**Comment by critterjohnson** [comment]
Or we could tighten the regex a little. I'll take a look this weekend; I had this passing unit tests locally originally but they're failing now.

**Comment by azdagron** [comment]
Thanks again for putting this fix together @critterjohnson. I was finally able to get #5076 opened to more robustly handle cgroups v2 support. This fix should no longer be necessary. So I'll go ahead and close out the PR.

Do you think you'd have time to test #5076 against your crio setup? You'd need to check it out and build an agent image. Then, to enable it, you have to turn on the new support in the agent configuration for the "k8s" WorkloadAttestor plugin.

```
WorkloadAttestor "k8s" {
     .... other config values ....
     use_new_container_locator = true
}
```
If enabled, you should see a line like the following on startup: 
```
INFO[0000] Plugin loaded                                 external=false plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog
INFO[0000] Using the new container locator               external=false plugin_name=k8s plugin_type=WorkloadAttestor subsystem_name=catalog
```

**Comment by critterjohnson** [comment]
@azdagron Would love to try this on our env - I'll do it next week. Thanks!

**Comment by azdagron** [comment]
@critterjohnson awesome! For what it's worth, the nightly image has been built with the change, so it should be a little easier to test with.

**Pull request closed without merging**
