### PR TITLE
Add Environment variable config templating support

### LINKED ISSUE #1364: Support environment variable expansion within configuration files.
* **Version**: NONE
* **Platform**: ALL
* **Subsystem**: SERVER, AGENT, PLUGIN

At present, it seems I need to provide sensitive information (e.g., database passwords) within my configuration files.  I want my environment under configuration control and that is a bit problematic in a Kubernetes environment when using the instructions provided.  If I used a ConfigMap as described, I would have the ConfigMap in plain text in my repository.  

I can use a Secret instead and then something like Kubeseal to encrypt the value before checking it into my repository but then I have a bunch of much less sensitive information controlled within a secret and so changing something trivial (i.e., log level) requires I grab the decrypted secret from Kubernetes, decode the config file, make my change, re-encode the config file, re-encrypt the config file and push.

It seems to me that a much more robust solution would be to support environment variable expansion within the configuration file.  Almost all Hashicorp products using HCL support this in one form or another so it is a thing.

I think there are a few approaches that would work (in order of simplicity):

1. Simply perform variable expansion on the configuration file before actually parsing.
2. Provide an interpolation syntax that is processed after parsing (e.g., `"${env SECRET}"`)

### PR DESCRIPTION
**Pull request by mcpherrinm**
**Pull Request check list**
 docs, tests updated.

**Affected functionality**
Server and agent config file

**Description of change**
This adds a flag -expandEnv which causes the config file to have environment variables expanded in them.

This makes it easier to template configurations, for example between a staging and production environment which may have different trust domains, mysql URLs, etc.
As well, it more safely allows things like Mysql passwords to be provided, avoiding keeping them in configuration files.

**Which issue this PR fixes**
fixes #1364, #1303

### CODE REVIEW

**Comment by azdagron** [comment]
Build is broken but once that has been fixed, i'm happy to get this in.... let me know if you need me to pick up the fix.

**Comment by mcpherrinm** [comment]
I think we should add this to the agent too

We should also have a test too

Sorry, been busy and won't have time to look at this for a little while.  I would very much appreciate if somebody else could push it over the line, or else I'll get to it next week.

**Comment by mcpherrinm** [comment]
Pushed agent support, still need tests/docs

**Comment by mcpherrinm** [comment]
Pushed a test; still need documentation

**Comment by mcpherrinm** [comment]
Added documentation!  I think this PR is fully ready for review.

**Pull request merged**
