### PR TITLE
cherry-pick "Switch to Informers for k8sbundle notifier (#2857)"  into v1.2

### PR DESCRIPTION
**Pull request by denis-tingaikin**
Signed-off-by: Faisal Memon <fymemon@yahoo.com>

**Pull Request check list**

- [ ] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

**Description of change**
The problem that was fixed in https://github.com/spiffe/spire/issues/2827 is critical for third part applications and it could be useful to propagate the fix into v1.2.1

Related to https://github.com/spiffe/spire/issues/2827#issuecomment-1074370117

### CODE REVIEW

**Comment by denis-tingaikin** [comment]
@azdagron Could you have a look?

**Comment by denis-tingaikin** [comment]
@azdagron OK. Am I getting it correct that `v1.2.2` will be released in next days?

**Comment by azdagron** [comment]
We are planning on picking the release commit today or tomorrow. It will likely release 7 days from then. We are hoping to release on Apr 6th. You can see the milestone here: https://github.com/spiffe/spire/milestone/17.

**Comment by denis-tingaikin** [comment]
@azdagron We're planning release NSM on April 4th. Do you have in mind any options on how we can get this commit till our release?

**Comment by azdagron** [comment]
I think you have two options.
1. Check out SPIRE v1.2.1, cherry-pick in the fix, build and host your own SPIRE image that NSM uses.
2. Grab a nightly SPIRE image which includes the fix. You'd probably still want to tag this and push it into your own registry so you weren't pulling nightly on every deploy (which is a moving target).

**Comment by azdagron** [comment]
> nightly SPIRE image

I mean this: docker pull ghcr.io/spiffe/spire-server:nightly

Our CI/CD pipeline builds and replaces that every night.

**Comment by denis-tingaikin** [comment]
@azdagron we also can move our release date. How sure are you about the Apr 6 release date?

**Comment by azdagron** [comment]
@denis-tingaikin we have chosen our candidate commit and barring discovery of any sort of release blocking bug or critical issue, will be releasing on April 6th. See the release issue #2899. I don't anticipate any problems.

**Comment by azdagron** [comment]
@denis-tingaikin just a quick heads up, that there has been an announcement of a [PRIVATE](https://go.dev/security) security release on April 7th for Go:

```
We plan to issue Go 1.18.1 and Go 1.17.9 on Thursday, April 7th.

These minor releases include a PRIVATE security fix to the standard library.

Following our security policy, this is the pre-announcement of those releases.
```

We're going to hold off our release until we can assess the impact and the mitigating Go toolchain is released. It is likely that we'll be able to release on the 7th, assuming a toolchain update is the only necessary mitigation.

**Pull request closed without merging**
