### PR TITLE
Update workflow Ubuntu to 22.04

### PR DESCRIPTION
**Pull request by faisal-memon**
**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [x] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**
Various github actions

**Description of change**
Updates ubuntu versions in all workflows to 22.04

**Which issue this PR fixes**
N/A

### CODE REVIEW

**Comment by azdagron** [comment]
The changes to MAXCHECKS seem unnecessary? MAXCHECKS should be evaluating to the proper value in those bash arithmetic expressions without the $. Are you seeing differently?

**Comment by faisal-memon** [comment]
> The changes to MAXCHECKS seem unnecessary? MAXCHECKS should be evaluating to the proper value in those bash arithmetic expressions without the $. Are you seeing differently?

No it's not necessary. I was trying a few different things to see what's causing the failure.

**Comment by MarcosDY** [comment]
Looks like when you upgraded ubuntu to 22.04, docker start to use cgroupv2, that cause that `/proc/${PID}/cgroup` is containing only `0::/`, so spire is unable to get container ID, 
in order to have a success upgrade we must address #4004

**Comment by azdagron** [comment]
I'm working on #4004 this week.

**Comment by azdagron** [comment]
Integration tests are now passing, @faisal-memon. Feel free to just squash my commits in with your other edits when you fix DCO.

**Comment by faisal-memon** [comment]
Backed out all the unnecessary changes

**Comment by azdagron** [comment]
Thanks @faisal-memon. I think you need to re-introduce one change (shellcheck is complaining during linting). Afterwards feel free to squash the changes, fix up DCO, and force-push. I'll re-review the final change and then we can get this merged!

**Comment by faisal-memon** [comment]
> Thanks @faisal-memon. I think you need to re-introduce one change (shellcheck is complaining during linting). Afterwards feel free to squash the changes, fix up DCO, and force-push. I'll re-review the final change and then we can get this merged!

@azdagron Should be good to go now.

**Review by azdagron — APPROVED** [review]
Thank you, @faisal-memon!

**Pull request merged**
