### PR TITLE
 Add CanReattest flag in node attestor plugins and in datastore

### PR DESCRIPTION
**Pull request by dfeldman**
The idea here is to add a new CanReattest boolean flag attached to attested nodes. 
This indicates whether the attestation can be easily repeated (such as a TPM-based or x509pop attestation), or is TOFU only (like an IID attestation). 
Eventually, we'll have a feature to clear out all the attested nodes where CanReattest=true when needed. 

#1836 

Signed-off-by: Daniel Feldman <dfeldman.mn@gmail.com>

### CODE REVIEW

**Comment by dfeldman** [comment]
This is failing now because it depends on a change that is in spire-plugin-sdk but hasn't yet been tagged, I think I need the new tag on that repo

**Comment by azdagron** [comment]
No explicit tag is needed on the SDK repo. To pull in changes between release tags, you can use the exact commit, which will update the go.mod to use a pseudo version.

i.e.
```
$ go get github.com/spiffe/spire-api-sdk@<commit hash>
```

**Comment by dfeldman** [comment]
Thanks!

**Comment by azdagron** [comment]
Hi @dfeldman! We have a planned release in a few weeks. It will be a minor release, which is when we introduce deprecation and migration related code. For this feature, even if the full PR won't be ready by then, it would be great to at least get the database migration merged. Would you mind creating a separate PR with just the migration code?

**Comment by dfeldman** [comment]
Yes of course. I would also like to add another field -- the "hint" string on registration entries, in order to support the SVID Hint feature in SPIFFE. Can we do these at the same time?

**Comment by azdagron** [comment]
Yes, that would be just fine.

**Comment by azdagron** [comment]
@dfeldman, enough time has passed that there are many conflicts that need resolved. Also, some of these changes already made their way into `main`. It would be nice to look at this change after it has been rebased on top of `main`.

**Review by azdagron — COMMENTED** [review]
Thanks @dfeldman, I think this is looking good. The only thing I noticed is that I believe we missed setting CanReattest to true for the tpmdevid and psat node attestors which also support re-attestation.

**Review by azdagron — APPROVED** [review]
\o/

**Pull request merged**
