### PR TITLE
Skip k8s-workload-registrar when publishing to ghcr.io

### PR DESCRIPTION
**Pull request by marcofranssen**
**Pull Request check list**

- [ ] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

**Description of change**

**Which issue this PR fixes**

### CODE REVIEW

**Comment by marcofranssen** [comment]
This fixes the ghcr.io publish so we don't have to revert.

**Comment by marcofranssen** [comment]
You can test by adding following to the script.

```diff
+echo ${OCI_IMAGES[@]}
+
+exit 1
+
```

and see here my test

```shell
$ .github/workflows/scripts/push-images.sh v1.5.3 -scratch
spire-server spire-agent oidc-discovery-provider
$ .github/workflows/scripts/push-images.sh v1.5.3    
spire-server spire-agent k8s-workload-registrar oidc-discovery-provider
```

**Comment by marcofranssen** [comment]
We need a rerun off this flaky test that fails in almost every PR.

https://github.com/spiffe/spire/actions/runs/3642778492/jobs/6150288795

**Review by rturner3 — APPROVED** [review]
LGTM, thanks for providing the fix on short notice!

**Pull request merged**
