### PR TITLE
SPIRE agent knows to reattest if SVID has CanReattest set

### PR DESCRIPTION
**Pull request by akaloti**
**Pull Request check list**

- [X] Commit conforms to CONTRIBUTING.md?
- [X] Proper tests/regressions included? (N/A)
- [X] Documentation updated? (N/A)

**Affected functionality**
node reattestation

**Description of change**
Currently, if one attempts to perform node reattestation (with a custom NodeAttestor plugin that supports node reattestation and by setting the experimental feature flag `reattest_to_renew` in both the server and agent configuration files), the SPIRE server recognizes that the node must reattest, but the SPIRE agent does not recognize this, due to a bug. This results in the SPIRE agent crashing when it attempts to renew its SVID instead of reattest, resulting in the below error message:

```
ERRO[0009] Agent crashed                                 error="failed to renew agent: rpc error: code = PermissionDenied desc = agent can't renew SVID, must reattest"
```

The bug occurs because although the SVID has `CanReattest` set by the node attestor plugin I'm using, the SPIRE agent code does not save that field to `agent-data.json`, resulting in it being set to false, as shown below. The SPIRE agent doesn't recognize the SVID is reattestable, so -- at [this if statement](https://github.com/spiffe/spire/blob/main/pkg/agent/svid/rotator.go#L148) -- it goes into `rotateSVID()` instead of `reattest()`.

```
{"svid":...,"bundle": ...,"reattestable":false}
```

This pull request makes it so that the `CanReattest`/`reattestable` field is properly saved for the SVID, resulting in it being saved as `true` instead of `false` in `agent-data.json` (if the plugin set that field to `true`) and allowing the SPIRE agent to know it needs to perform reattestation instead of renewing its SVID:

```
DEBU[0010] Reattesting node                              subsystem_name=manager
INFO[0010] Successfully reattested node                  spiffe_id="spiffe://example.org/spire/agent/..." subsystem_name=manager
```

### CODE REVIEW

**Comment by rturner3** [comment]
Hi @akaloti, thank you for tracking this down and submitting the fix!

The commit in this pull request is missing [DCO](https://github.com/spiffe/spiffe/blob/main/CONTRIBUTING.md#sending-a-pull-request). Could you update the commit with `git commit --amend --no-edit --signoff` and force push your branch to update the PR with the required signature information?

**Comment by faisal-memon** [comment]
I can review this one.

**Comment by akaloti** [comment]
> Hi @akaloti, thank you for tracking this down and submitting the fix!
> 
> The commit in this pull request is missing [DCO](https://github.com/spiffe/spiffe/blob/main/CONTRIBUTING.md#sending-a-pull-request). Could you update the commit with `git commit --amend --no-edit --signoff` and force push your branch to update the PR with the required signature information?

Done.

**Review by faisal-memon — APPROVED** [review]

**Review by rturner3 — APPROVED** [review]
Thanks, @akaloti!

**Pull request merged**
