### PR TITLE
Fix error in Docker workload attestor documentation

### PR DESCRIPTION
**Pull request by scotte**
Signed-off-by: Scott Emmons <scott@scytale.io>

### CODE REVIEW

**Comment by ZymoticB** [comment]
That's not an error. This documentation was written by someone working at a company which labelled their container at launch with an "environment". That's a separate concept from the environment variables on that container.

**Comment by scotte** [comment]
In that case, using 'env' as a label example is a poor choice as it conflates the use of `env` between 'env' and 'label' examples. Given that, the example should be rewritten to be more clear:

+ Avoid use of `env` in a "label" example, as it causes confusion.
+ Add an example using environment variables

**Comment by ZymoticB** [comment]
Sure, it was written before the environment variable attestation was available. I agree its confusing at this point. Both of your suggestions would be great.

**Comment by scotte** [comment]
I'm glad you commented that I missed the whole point of the original example. I'll update this PR with the above in mind. Thanks!

**Comment by scotte** [comment]
@ZymoticB does this make more sense? Thanks!

**Comment by ZymoticB** [comment]
LGTM

**Pull request merged**
