### PR TITLE
Add pagination to listEntries cache hydration

### PR DESCRIPTION
**Pull request by stevend-uber**
**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [x] Proper tests/regressions included?
- [x] Documentation updated?

**Affected functionality**
This PR adds pagination while spire-server makes calls to spire-db to list entries.

**Description of change**
For small databases, this will not affect them. For large deployments of spire-db, this will ensure that rather than a single long-latency call to list the entries table, we make multiple smaller calls.

I tested against a spire-server with 40gb of memory and a spire-db with 1million entries. For this setup, we noticed that setting pagination was almost a boolean value where page sizes of 10k, 50k, 100k all resulted in a full-entry-cache sync of approximately 17seconds with a higher connection/lower latency count for the smaller page sizes. 

I ultimately chose 10k as the page size so that any failed calls to the db were more lightweight to retry if we ever wanted to add retry logic to each page cursor. 
**Which issue this PR fixes**
https://github.com/spiffe/spire/issues/4488

### CODE REVIEW

**Comment by azdagron** [comment]
Hey @stevend-uber, thanks for the contribution! Would you mind updating the events-based cache hydration code as well as part of this PR? It would be good to have parity on the implementations.

**Comment by azdagron** [comment]
I think the only thing missing here is unit tests that exercise the pagination. To facilitate this, you might consider making the page limit a `var` so that the test can drop the limit to a handful of entries or something.

**Comment by stevend-uber** [comment]
Updated

**Comment by azdagron** [comment]
Great! thanks! There are some lint failures now.

**Review by azdagron — APPROVED** [review]
\o/

**Pull request merged**
