### PR TITLE
SkipBlockDevice check.

### PR DESCRIPTION
**Pull request by mlakewood**
As an extra security measure we match the ENI attach time to the block attach time. If they diverge then
    we know that the box has been rebooted possibly malicously. On AWS however there is a configuration that
    causes this check to not work. To avoid performing this check we have added a skip_block_device flag in
    the configuration to not attempt this check. As this is a potential security hole, you must explicitly
    set this flag otherwise node attestation will fail.

**Pull Request check list**

- [x ] Commit conforms to CONTRIBUTING.md?
- [] Proper tests/regressions included?
- [x] Documentation updated?

**Affected functionality**
As an extra security measure we match the ENI attach time to the block attach time. If they diverge then we know that the box has been rebooted possibly malicously. On AWS however there is a configuration that causes this check to not work. To avoid performing this check we have added a skip_block_device flag in the configuration to not attempt this check. As this is a potential security hole, you must explicitly set this flag otherwise node attestation will fail.

**Which issue this PR fixes**
`fixes #<410>`

### CODE REVIEW

**Comment by evan2645** [comment]
awesome, thanks for this @mlakewood!

is it possible to detect this condition and automatically skip it instead? perhaps by detecting ephemeral storage vs ebs? my concern here is that by making this configurable, it's all-or-nothing. folks with mixed environments will likely want to benefit from this check on ebs-backed instances while at the same time skipping it for ephemeral instances

**Comment by mlakewood** [comment]
Hmm, so we could auto-detect this. The reason I didnt do that is that you are taking away a safety mechanism (granted, one that you couldnt take advantage of). I think I would prefer for the process to error out, that lower the security level of the process.

For the DCO, do I just need one commit with the -s?

**Comment by evan2645** [comment]
> I think I would prefer for the process to error out, that lower the security level of the process.

The problem with this is that it actually lowers the security stance, rather than strengthen it. Imagine the following scenario:
I am an AWS user, and I prefer to use EBS-backed instances, but still have a handful of ephemeral instances. Without ephemeral volume detection, I have two options: 1) don't use SPIRE on the ephemeral hosts, or 2) disable the volume check, leaving my EBS-based hosts open to attack.

We may wish to keep a configurable allowing users to disable this particular check (maybe there are workflows under which this is normal?), but I don't think we can get away without doing detection.

>For the DCO, do I just need one commit with the -s?

Every commit needs the -s. We went to the DCO after becoming a CNCF project, you can read more about DCO here: https://github.com/probot/dco#how-it-works

**Comment by mlakewood** [comment]
Is there something that makes it an all or nothing configuration across an entire fleet? Its relatively trivial to have configurations change from one host to another.

**Comment by evan2645** [comment]
Ah, yes, the reason that this config applies broadly is because it is being set on SPIRE server and not agent, and it is expected that a single SPIRE server manages an entire trust domain, which may comprise 100s or 1000s of machines

**Comment by mlakewood** [comment]
Ahh I see. yeah that could be a bit annoying.

**Comment by evan2645** [comment]
@mlakewood I think ultimately there may be workflows that make this check problematic, so having it be configurable is 👍. We'll take this contrib but leave #410 open so we can write the detection in at that time. If you can update your commit with a Signed-off-by line, we'll merge this in. Thanks!!

**Comment by mlakewood** [comment]
Opened a fresh PR over here -> https://github.com/spiffe/spire/pull/424

closing this in preference to that.

**Pull request closed without merging**
