### PR TITLE
Remove periods at the end of log and error messages

### PR DESCRIPTION
**Pull request by SilvaMatteus**
Signed-off-by: Matteus Silva <silvamatteus@lsd.ufcg.edu.br>

**Pull Request checklist**

- [X] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

Changes in log and error messages.

**Description of change**

According to CONTRIBUTING.md, section [Logs and Errors](https://github.com/spiffe/spire/blob/master/CONTRIBUTING.md#logs-and-errors), log messages and error messages should not end with periods.

### CODE REVIEW

**Review by rturner3 — APPROVED** [review]
Thanks for cleaning these up, @SilvaMatteus !

**Review by amartinezfayo — APPROVED** [review]

**Comment by amartinezfayo** [comment]
Thanks for this @SilvaMatteus!
Please notice that some tests assert the logged messages and must be updated as part of this change.
You can run `make test` to see what tests are failing.

**Comment by SilvaMatteus** [comment]
@amartinezfayo you're right. I missed this. Thanks.

**Review by amartinezfayo — APPROVED** [review]
Thanks @SilvaMatteus!

**Pull request merged**
