### PR TITLE
Update to controller-runtime 0.10.0

### PR DESCRIPTION
**Pull request by faisal-memon**
Signed-off-by: Faisal Memon <f.memon@f5.com>

**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [x] Proper tests/regressions included?
- [x] Documentation updated?

**Affected functionality**
k8s-workload-registrar reconcile and CRD modes

**Description of change**

1. Updates controller-runtime to 0.10.0 and Kubernetes dependancies to v0.22.1
~~2. With the controller-runtime update, switch to v1 ValidatingWebhookConfiguration for CRD mode~~

Tested with both CRD and reconcile modes to make sure everything still works as expected.

**Which issue this PR fixes**

### CODE REVIEW

**Comment by rturner3** [comment]
I haven't looked into the details of this upgrade yet, but was initially curious if there was anything preventing us from bumping the k8s.io and controller-runtime dependencies to the latest versions (0.22.2 and 0.10.0, respectively)?

**Comment by faisal-memon** [comment]
> I haven't looked into the details of this upgrade yet, but was initially curious if there was anything preventing us from bumping the k8s.io and controller-runtime dependencies to the latest versions (0.22.2 and 0.10.0, respectively)?

controller-runtime 0.10.0 uses v0.21.3 Kubernetes api compared to v0.21.4 for controller-runtime 0.9.7. I thought that was a little weird. 0.10.0 is also the first release of a new major version and I was being a little cautious. I figure there will be 0.10.1 release fairly soon that bumps the Kubernetes api dependancies and we can switch to that when it's released.

**Comment by faisal-memon** [comment]
> > I haven't looked into the details of this upgrade yet, but was initially curious if there was anything preventing us from bumping the k8s.io and controller-runtime dependencies to the latest versions (0.22.2 and 0.10.0, respectively)?
> 
> controller-runtime 0.10.0 uses v0.21.3 Kubernetes api compared to v0.21.4 for controller-runtime 0.9.7. I thought that was a little weird. 0.10.0 is also the first release of a new major version and I was being a little cautious. I figure there will be 0.10.1 release fairly soon that bumps the Kubernetes api dependancies and we can switch to that when it's released.

I misunderstood the release notes. controller-runtime 0.10.0 use v0.22.1 Kubernetes API. I think its ok to switch to 0.10.0.

**Comment by azdagron** [comment]
This is looking pretty good faisal, though I didn't see the following change mentioned in the description...

> With the controller-runtime update, switch to v1 ValidatingWebhookConfiguration for CRD mode

**Comment by faisal-memon** [comment]
> This is looking pretty good @faisal-memon, though I didn't see the following change mentioned in the description...
> 
> > With the controller-runtime update, switch to v1 ValidatingWebhookConfiguration for CRD mode

Hey @azdagron. I backed it off with https://github.com/spiffe/spire/pull/2540/commits/89244745cbde0e447175f66b626c020b89bf3720. We first need a SPIRE build with this PR in it, the current version won't work with v1 ValidatingWebhookConfiguration. Once its released Ill update the config.

**Comment by azdagron** [comment]
I see.In general, I think it's fairly important for the docs in main branch reflective of the capabilities of the code living in the main branch so that when a version is cut, somebody can check out that version tag and have a correct view of things. However, I don't have any good recommendations for this particular piece of documentation to accomplish that. I think we can probably come up with something, but that can happen at a later time.

Do you have cycles to fix the linting failures? Once those have been addressed I'm happy to merge this.

Thanks for the contrib!

**Comment by faisal-memon** [comment]
> I see. In general, I think it's fairly important for the docs in main branch to be reflective of the capabilities of the code living in the main branch so that when a version is cut, somebody can check out that version tag and have a correct view of things. However, I don't have any good recommendations for this particular piece of documentation to accomplish that. I think we can probably come up with something, but that can happen at a later time.
> 
> Do you have cycles to fix the linting failures? Once those have been addressed I'm happy to merge this.
> 
> Thanks for the contrib!

I think its good to reinvestigate the documentation bit. There is a bit of a disconnect.

The linter errors don't seem to be related to my changes. For example:
```
pkg/server/plugin/upstreamauthority/certmanager/certmanager_test.go:321:14: SA1019: fakeclient.NewFakeClientWithScheme is deprecated: Please use NewClientBuilder instead. (staticcheck)
						return fakeclient.NewFakeClientWithScheme(scheme), nil
```

Was the linter version updated recently?

**Comment by azdagron** [comment]
They are related to deprecation changes introduced by the updated controller-runtime.

**Comment by faisal-memon** [comment]
I see, updating now...

**Review by azdagron — APPROVED** [review]
\o/ thanks @faisal-memon !

**Pull request merged**
