### PR TITLE
Configure dependabot to automatically raise PRs for gomod dependencies

### PR DESCRIPTION
**Pull request by rturner3**
Dependabot is a tool that detects when package dependencies in a project are not referring to the latest versions and submits individual pull requests in the project to upgrade each dependency to the latest version. This should hopefully simplify the maintenance burden of keeping dependencies in sync and prevent us from being subject to vulnerabilities from old dependency versions.

The plugin is configured to run daily (Mon-Fri). I chose to have the bot run at a time when all maintainers are generally expected to be online and available to give all maintainers an opportunity to see the PRs. For now, I have limited it to raising at most five open PRs at any given time.

I have also excluded the SPIRE SDK packages from automatic upgrade since those dependency upgrades are managed manually as part of our release process.

### CODE REVIEW

**Review by azdagron — DISMISSED** [review]
Neat!

**Comment by MarcosDY** [comment]
may we exclude go-spiffe too?

**Comment by azdagron** [comment]
What would be the reason to exclude go-spiffe?

**Comment by MarcosDY** [comment]
we have control over it, and generally changes we apply there can require changes on SPIRE.
Of course it depends  about what change we are talking about...

**Comment by rturner3** [comment]
> we have control over it, and generally changes we apply there can require changes on SPIRE. Of course it depends about what change we are talking about...

The PRs raised by the bot still need to be approved by a maintainer. Most of us have pretty good context about what changes are coming in go-spiffe, so I'm not too concerned about dependabot at least automating the PR creation for us. We will definitely still want to evaluate the dependency upgrade and make sure SPIRE is not affected in an adverse way before accepting.

**Review by azdagron — APPROVED** [review]
\o/, thanks @rturner3

**Pull request merged**
