### PR TITLE
Fix linter dependency for go-check in Makefile

### PR DESCRIPTION
**Pull request by amartinezfayo**
The go-check dependency was not really enforced for the `make lint` task.
If go was not downloaded before, `make lint` fails.

### CODE REVIEW

**Comment by azdagron** [comment]
@amartinezfayo, does this fix #2913?

**Comment by amartinezfayo** [comment]
I think it's a different thing. This PR is to fix the fact that go was not being installed before running the linter (that was not needed by the time that #2913 was filed). The problem in #2913 seems to be that go is installed but then the path to run it is not found.

This PR is to fix this situation: https://github.com/spiffe/spire/runs/6042870281?check_suite_focus=true

**Review by azdagron — APPROVED** [review]
\o/

**Comment by azdagron** [comment]
Thanks for the clarification.

**Pull request merged**
