### PR TITLE
k8s-workload-registrar: Update README to clarify that k8s psat node attestor is not a requirement

### PR DESCRIPTION
**Pull request by bbarnes52**
The current wording is misleading according to https://tools.ietf.org/html/rfc2119

Signed-off-by: Brian Barnes <bgb@uber.com>

### CODE REVIEW

**Comment by azdagron** [comment]
Hi Brian. The k8s-workload-registrar does indeed require SPIRE server to use `k8s_psat` based node attestation. All three modes rely on this detail and create registration entries with that assumption. Can you help me understand why you felt it was not a requirement?

**Comment by bbarnes52** [comment]
Hey Andrew, thanks for educating me. Could I trouble you to explain a bit more about the need for this requirement? To answer your question, I didn't see any reason workload attestation would need to be coupled to a specific NodeSelector, though I'm sure I'm missing something.

**Comment by bbarnes52** [comment]
For instance, if we created node registration entries whose SpiffeIDs conform to `spiffe://<trust domain>/spire/agent/k8s_psat/<cluster>/<node UID>`, without using the k8s_psat node selector, would that meet the requirements of the k8s workload registrar?

**Comment by azdagron** [comment]
SPIRE's registration model requires registration of both 1) what a workload looks (i.e. selectors on the workload entry) and 2) where a workload runs (parent ID on the workload entry).

In the case of the k8s-workload-registrar, it is registering K8s workloads. With slight variation on the various modes, it needs to look at a workload PodSpec and figure out where that pod will run in order to successfully register that workload. The PSAT attestor is a logical choice because it's easy to figure out from the PodSpec which PSAT attested agent will be available to the Pod. There is no architectural requirement for PSAT, it's just the only attestation method currently supported by the registrar. Technically support could be added for other attestation methods, but the mapping between PodSpec and agent is less straightforward and would have to be figured out.

**Comment by azdagron** [comment]
> For instance, if we created node registration entries whose SpiffeIDs conform to spiffe://<trust domain>/spire/agent/k8s_psat/<cluster>/<node UID>, without using the k8s_psat node selector, would that meet the requirements of the k8s workload registrar?

You can't create node registration entries with that kind of SPIFFE ID shape today. SPIRE does not allow you to create registration entries where the target SPIFFE ID is in the reserved namespace (that namespace belongs to SPIRE node attestors).

**Comment by bbarnes52** [comment]
Got it, thanks for explaining. In case you're interested, the reason this doesn't work for us is that we do not run the spire components on kubernetes. At node attestation time, the kubelet isn't even running yet.

**Comment by azdagron** [comment]
Yeah, sounds like the k8s-workload-registrar, at least the way it currently operates isn't a good fit for your use case. I would be interested in knowing more about your particular use case though. We're teeing up some work soon to design a smoother K8s integration. It would be nice to accommodate your use case, if feasible.

**Comment by bbarnes52** [comment]
Absolutely. I work at Uber, perhaps you've met some of my colleagues. The salient details are:

1. We have a multiple schedulers running in prod (k8s, yarn, etc). Different schedulers operate on different pools of hosts. There is also a low-level scheduler that is responsible for scheduling the k8s components, spire control plane, and a handful of other low-level services.  
2. Spire-agent runs on every host (it is baked into the host image as a systemd unit). Every host in a given zone (we have a hybrid model with multiple cloud providers + onprem) currently uses the same NodeSelector, though different NodeSelectors are used in different zones (one for each cloud provider + onprem).

We are not opposed to running on spire on k8s per-se, it's just not feasible at the moment. Currently, the spiffeIDs allocated to agents take the form `spiffe://<trust_domain>/spire/agent/<zone>/<host_name>`, irrespective of what NodeSelector is used.

We would ideally be able to configure the k8s workload registrar to create registration entires whose parentID conform to the above spec. Would you be open to a PR that makes this attribute configurable? Else we can add this to our fork, not sure how common this problem will be for other users.

**Comment by bbarnes52** [comment]
@azdagron a more concrete proposal for your consideration:

It seems we could remove the requirement of using the k8s_psat node attestor by making it possible to set the parentID of a workload entry to the agent's spiffe ID (and disable the node reconciler). This would amount to adding a couple new config fields:
1. `disableNodeReconciler` If true, the k8s workload registrar does not create any node registration entries.
2. `agentPathTemplate`. Must be set if `disableNodeReconciler` is true, must match the `agentPathTemplate` value configured for the configured NodeAttestor  plugin (AWS, GCP, and x509Pop plugins all support this field). 

So for instance, I could configure something like:
```
disableNodeReconciler: true
agentPathTemplate: datacenter/$node
```
Where $node is a special substitution variable that is replaced by the k8s nodename at runtime

**Pull request closed without merging**
