### PR TITLE
[#4380] Allow custom entry ID in BatchCreateEntry

### PR DESCRIPTION
**Pull request by mjptree**
**Pull Request check list**

- [X] Commit conforms to CONTRIBUTING.md?
- [X] Proper tests/regressions included?
- [X] Documentation updated?

**Affected functionality**
With this change `BatchEntryCreate` requests that arrive with a user specified entry ID will honour this request and try to create a registration entry with the desired entry ID.

**Description of change**
The creation fails if a similar entry already exists, even if the requested entry ID does not match the ID of the existing entry. User specified registration entries are validated for allowable length of the ID and characters. Allowable characters with this change are `[A-Za-z0-9_-.]`.

**Which issue this PR fixes**
Resolves https://github.com/spiffe/spire/issues/4380.

### CODE REVIEW

**Comment by azdagron** [comment]
Thanks for putting this together, @mjptree! Are there remaining items you want to address before moving this out of draft? is it ready for review?

**Comment by mjptree** [comment]
> Are there remaining items you want to address before moving this out of draft? is it ready for review?

@azdagron Yes, thanks! I am currently also adding the command line arguments, then I think it should be ready for review.

**Comment by azdagron** [comment]
Excellent, @mjptree. Thanks again!

**Comment by mjptree** [comment]
I updated the datastore and the cli. I also added test on the entry service API layer. I think it's ready for review. Is it preferred if I merge latest changes from main, or if I rebase to it?

**Comment by azdagron** [comment]
Since it hasn't been reviewed, if you want to rebase and force-push that is fine. Once a review has started we usually prefer merge commits from main. We squash them when merging the PR anyway and it makes the review process a little simpler (force pushing makes it a little harder to tell what changed on the PR, especially if coupled with squashing)

**Review by azdagron — APPROVED** [review]
LGTM! Thanks for this @mjptree and sorry about the review latency.

**Pull request merged**
