### PR TITLE
Add config option for verbose split claims in JWT-SVIDs

### PR DESCRIPTION
**Pull request by Celant**
Signed-off-by: Josh Harris <me@celant.co.uk>

**Pull Request check list**

- [ ] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**
JWKS-SVID signer

**Description of change**
Adds a new `jwt_verbose_claims_enabled` server config option. In addition to the subject claim, if enabled, it will also add a `trust` and `workload` claim. These contain the Trust Domain and the Workload Identifier split out from the SPIFFE ID.

**Which issue this PR fixes**

### CODE REVIEW

**Review by amartinezfayo — COMMENTED** [review]
Thank you for this contribution, @Celant!

JWT-SVIDs issued by SPIRE already have the `sub` claim set to the SPIFFE ID of the workload to which it is issued.
Having the trust domain of the SPIFFE ID and the path of the SPIFFE ID inside the trust domain in separate claims doesn't seem to be needed in general, since the consumer of the JWT-SVID should be able to obtain that from the `sub` claim that we already have.

Could you tell us a little more about your use case and if it would be possible for your applications to parse the `sub` claim to obtain the same?

**Comment by Celant** [comment]
@amartinezfayo Unfortunately parsing the `sub` claim out of the JWT isn't working well for us. Our use-case here is for Vault, and using the JWT-SVID in Vault policy templates. We can parse out any claim in the JWT for use in our policy templates, but the default `sub` claim is causing us problems. The `spiffe://` prefix of the SPIFFE ID is causing us headaches, as a few different systems are detecting the URI scheme as an empty folder due to the double-slash and stripping it out.

This 'verbose claims' option simply takes the existing SPIFFE ID, and adds both the workload identifier and trust domain as explicit extra claims. This means we're no longer needing to parse a full URI, and it will allow us to use the workload identifier in our Vault policy templates without issues.

I'd also like to adapt this change in a follow-up PR at some point, to rework claims in a way that also covers #1848. In my mind, a similar system to Vault's policy templating could really suit this. I.e. adding a list of extra claims to the SPIRE config. Each claim can contain a Golang template, so the users have full control over the contents of the claim, and the template can be populated with attested properties of the workload. That, however, is a discussion for another time as this PR is the urgent first step for us 🙂

**Comment by amartinezfayo** [comment]
Thank you for the details, @Celant. Are the JWT-SVIDs being parsed by Vault's built-in JWT/OIDC Auth Method? Or is this consumed by a custom plugin in Vault? We are trying to understand if there is a lack of flexibility in Vault or what is causing the problem with the content of the `sub` claim.

**Comment by amartinezfayo** [comment]
Discussed this offline with @Celant. #3253 would provide a solution for this.

**Pull request closed without merging**
