### PR TITLE
Update grpc to v1.36.0 and proto to v1.26.0

### PR DESCRIPTION
**Pull request by dragcp**
Signed-off-by: ramand.dragcp <dheepak.gcp@gmail.com>

**Pull Request check list**

- [*] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**
This was split off from #2172 

**Description of change**
We are upgrading the version of grpc and proto dependencies

**Which issue this PR fixes**

### CODE REVIEW

**Comment by azdagron** [comment]
Hmm, did `make generate` not regenerate any of the protobuf code?

**Comment by dragcp** [comment]
Yes. "make generate" is not generating those files. 

I have now done "make generate-check" which generates the files and then fails. I have committed the generated files, rebased and repushed

**Comment by azdagron** [comment]
Thanks!

**Review by azdagron — APPROVED** [review]

**Comment by dragcp** [comment]
Calling generate-check ( or protogen-check ) internally touches all the .proto files. 

Calling generate only picks up the proto files that have been touched by me. That is why it didn't regenerate the files in the first attempt

**Comment by azdagron** [comment]
Yeah, it's also supposed to regenerate when you move to a new version of the tool, but in your case, your build cache already had the new tool from working on the other PR, so it didn't rebuild. We're not really saving much time trying to be smart about regeneration since it is quick and idempotent. I'll probably tweak the makefile to just regenerate always.

**Pull request merged**
