### PR TITLE
remove superfluous node attest metric

### PR DESCRIPTION
**Pull request by amoore877**
Signed-off-by: Andrew Moore <andrew.s.moore@uber.com>

**Pull Request check list**

- [X] Commit conforms to CONTRIBUTING.md?
- [X] Proper tests/regressions included?
- [X] Documentation updated?

**Affected functionality**
`node_attest` metric

**Description of change**
There are currently metrics of `node_attest` and `node_attestor_new_svid`.
`Attest` function in agent starts with `node_attest`, which captures attempting loading of keys / bundles from the key manager and on failure attest with the server to get a new svid
`node_attestor_new_svid` captures the attempt to attest with the server to get a new svid

`node_attest` should be removed. It is superfluous given the `node_attestor_new_svid` metric, measuring only file operations in addition to measuring what `node_attestor_new_svid` already takes care of.

**Which issue this PR fixes**
N/A

### CODE REVIEW

**Comment by APTy** [comment]
@amoore877 Thanks for bringing this up. It seems like the `node_attestor_new_svid` metric provides meaningful insight into the node attestation process. Meanwhile, the `node_attest` metric is a superset of node attestation, and it also includes things that are probably not worth measuring, like how long it takes to load an svid from disk. Given this, what do you think about removing the `node_attest` metric entirely?

**Comment by amoore877** [comment]
> @amoore877 Thanks for bringing this up. It seems like the `node_attestor_new_svid` metric provides meaningful insight into the node attestation process. Meanwhile, the `node_attest` metric is a superset of node attestation, and it also includes things that are probably not worth measuring, like how long it takes to load an svid from disk. Given this, what do you think about removing the `node_attest` metric entirely?

I think it's valuable to keep, if only because it can indicate specific failure conditions on agent startup

**Comment by APTy** [comment]
> I think it's valuable to keep, if only because it can indicate specific failure conditions on agent startup. We may also introduce logic later that adds more, or takes away, some of this init processing (true overhead task, key manager changes...), and it would be valuable to know the latency differences.

What is it really measuring though? It seems like only file read latencies, which aren't super meaningful to operators. If we later introduce logic that adds latency that is meaningful to observe, we should consider adding init metrics at that time. But as we do these metrics tweaks, if we find things that aren't useful, we should clean them up. I think this instance is a case of a metric that was added early on, and now only serves as cruft that can be cleaned up.

As a concrete example, #1257 suggests adding the ability for agents to re-attest, which implies that `Attest()` could be invoked at times other than init. Do we rename the metric at that point? Or move it down to just measure the file reads? Either way, the future is uncertain, and removing this metric provides us with more flexibility for whatever future comes.

**Comment by APTy** [comment]
Thanks @amoore877!

**Pull request merged**
