### PR TITLE
k8sbundle notifier: fallback to in-cluster creds by default

### LINKED ISSUE #3518: k8sbundle notifier plugin throws an error if kube_config_file_path is not provided
We (w/@dentrax) followed up on the [documentation](notifier_k8sbundle.md) of the _k8sbundle_ plugin, and it says if the `kube_config_file_path` parameter is not provided, in-cluster credentials will be used, however, we saw an error once we try to configure the k8sbundle notifier plugin like the following:

```hcl
    Notifier "k8sbundle" {
        plugin_data {
           clusters = {
             "demo-cluster" = {
                namespace = "test"
			}  
          }
        }
      }
    }
```

> kube_config_file_path | The path on disk to the kubeconfig containing configuration to enable interaction with the Kubernetes API server. If unset, it is assumed the notifier is in-cluster and in-cluster credentials will be used.
-- | --

We investigated the error a little bit and saw the following code part that requires `kube_config_file_path` must be set in the configuration of the plugin:

https://github.com/spiffe/spire/blob/bfa325e021e1bb53a5c4e9b376a9422bd63a1416/pkg/server/plugin/notifier/k8sbundle/k8sbundle.go#L137

So, I think we should remove this line and add a warning message to inform people that in-cluster credentials will be used.

* **Version**: 
* **Platform**: 
* **Subsystem**:

### PR DESCRIPTION
**Pull request by Dentrax**
Fixes #3518

Signed-off-by: Furkan <furkan.turkal@trendyol.com>
Co-authored-by: Batuhan <batuhan.apaydin@trendyol.com>

cc @developer-guy 

**Pull Request check list**

- [X] Commit conforms to CONTRIBUTING.md?
- [X] Proper tests/regressions included?
- [ ] Documentation updated? (Already up-to-date)

**Affected functionality**

**Description of change**
See the linked issue.

**Which issue this PR fixes**
Fixes #3518

### CODE REVIEW

**Comment by faisal-memon** [comment]
Is this logic correct? If we have multiple clusters, I think at max 1 should be the default in cluster. The others should have to specify a kubeconfig.

**Comment by azdagron** [comment]
I agree with @faisal-memon. It seems that _at most_ you'd be able to use in-cluster credentials for just one of the cluster definitions...

**Comment by Dentrax** [comment]
> at max 1 should be the default in cluster

Oh, that makes sense! Updated logic and test according to this use-case.

**Comment by developer-guy** [comment]
kindly ping ☝️

**Comment by amartinezfayo** [comment]
Thank you @Dentrax for taking the time to work through this.
This change does not consider that a default in-cluster configuration can be specified through the top-level configuration, which is the allowed way to have a configuration that pushes bundle contents from an in-cluster SPIRE Server.

The `clusters` section assumes that those clusters are remote clusters and need a `kube_config_file_path` setting.
I've filed #3543 to clarify the documentation.

Closing this PR.

**Pull request closed without merging**
