### PR TITLE
Extend unix workload attestor

### PR DESCRIPTION
**Pull request by Kaizhe**
Signed-off-by: Kaizhe Huang <khuang@aurora.tech>

**Pull Request check list**

- [ x] Commit conforms to CONTRIBUTING.md?
- [ x] Proper tests/regressions included?
- [ x] Documentation updated?

**Affected functionality**

Extend the Unix workload attestor.

**Description of change**

Extend unix workload attestor to support two other selectors:
1. `process_name`: the process name is the executable without the absolute path. Though some security concerns may arise to use such selector (it should be documented), it provides flexibility for binary which is built under random directory (e.g. bazel)
2. `arg1`: the first argument of the command line. It supports scenario using interpret language like python. `python hello.py`

**Which issue this PR fixes**

### CODE REVIEW

**Comment by SilvaMatteus** [comment]
Hi @Kaizhe!

Maybe it would be good to support more than just the first argument. WDYT about using the entire arguments string as a selector too?

**Comment by azdagron** [comment]
This kind of thing has been discussed before (#2426). The challenge here is that the command line arguments that the agent can observe, at least on linux, come from /proc/pid/cmdline. However, that value is _not_ a snapshot from the OS at the time the process was launched, but rather, pulled from the process address space. This means that it is susceptible to modification by the process itself and cannot be relied on as an accurate measurement.

What would you like to attest with these selectors?

**Comment by Kaizhe** [comment]
> This kind of thing has been discussed before (#2426). The challenge here is that the command line arguments that the agent can observe, at least on linux, come from /proc/pid/cmdline. However, that value is _not_ a snapshot from the OS at the time the process was launched, but rather, pulled from the process address space. This means that it is susceptible to modification by the process itself and cannot be relied on as an accurate measurement.
> 
> What would you like to attest with these selectors?

@azdagron Thanks for raising the concerns and I agree with the concerns. The may usage for `cmdline/arguments` are for attesting interpret script like python. If the python scripts are run in a non-containerized build environment, there is no way to differentiate each python script's identity which is another security concern. 

Can we emphasize the security concerns in the doc and allow users to select carefully ?

Thanks,

Kaizhe

**Comment by azdagron** [comment]
Yes, we definitely would benefit by figuring out a way to attest the workload being executed in an interpreted environment. I personally don't think cmdline args are appropriate, but we can chat about it with other maintainers on the contributor sync meeting tomorrow.

Is it possible to segregate different script executions by user account and use the user account as the selector? If every interpreter process runs as the same user, then all the scripts are more or less in the same security domain anyway...

**Comment by Kaizhe** [comment]
> Yes, we definitely would benefit by figuring out a way to attest the workload being executed in an interpreted environment. I personally don't think cmdline args are appropriate, but we can chat about it with other maintainers on the contributor sync meeting tomorrow.
> 
> Is it possible to segregate different script executions by user account and use the user account as the selector? If every interpreter process runs as the same user, then all the scripts are more or less in the same security domain anyway...

Andrew, what you suggested definitely works however it does require a huge process change both on the developers side as well as the infra side. The scripts (e.g. python script) usually need to access different cloud resources (e.g. s3), so the IAM mapping drive us to separate service identity by script name. 

Please raise it on my behalf, I would be more than happy to have a discussion with you and the maintainers f2f.

**Comment by azdagron** [comment]
We had a chance to discuss this today in the [contributor sync](https://github.com/spiffe/spiffe/blob/main/community/sig-spire/README.md#spire-contributor-sync) call. To summarize our thoughts:
1. /proc/pid/cmdline is not a safe source for attestation data (can be manipulated by workloads)
2. Extending the workload attestor to produce these selectors is therefore dangerous, even with an security consideration mentioned in the documentation. People don't always read documentation, especially if they pick up a config section from an example or something.
3. If this selector is available, folks who find themselves in a similar situation as yourself may reach for it just because it is easy to pick up without fully exploring more robust solutions.

Because of the above points, we're hesitant to extend the official built-in unix workload attestor in this direction. However, if you've weighed the risk and find it acceptable, you can always implement you're own [Workload Attestor](https://github.com/spiffe/spire-plugin-sdk) custom to your own environment.

We're still _very_, _very_ interested in figuring out a robust solution for workloads being executed by an interpreter, if you're interested, we can continue a discussion in #2426 and work towards a resolution we can all be happy with.

I'll go ahead and close out this PR for now.

**Comment by Kaizhe** [comment]
Thank you for the response!

**Comment by Kaizhe** [comment]
@azdagron , what about process name ?

**Pull request closed without merging**
