### PR TITLE
Fix issue with socketPath handling

### PR DESCRIPTION
**Pull request by lumjjb**
Signed-off-by: Brandon Lum <lumjjb@gmail.com>

**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [x] Proper tests/regressions included? 
- [x] Documentation updated?

**Affected functionality**

**Description of change**

Bug fix, currently, `socketPath` is not respected in the server config file.

This is due to a bad interaction between https://github.com/spiffe/spire/blob/main/cmd/spire-server/cli/run/run.go#L298 and https://github.com/spiffe/spire/blob/main/cmd/spire-server/cli/run/run.go#L314

**Which issue this PR fixes**

### CODE REVIEW

**Comment by azdagron** [comment]
Hmm, confirmed. That is surprising. We have tests that were supposedly covering [this](https://github.com/spiffe/spire/blob/daf3f13cba27dfe6835fe8426e4ecc5cc1804f17/cmd/spire-server/cli/run/run_test.go#L385). I haven't dug into it myself, do you know why they didn't catch this?

**Comment by lumjjb** [comment]
hmm i see looks like the test for merge is taking in `cliInput`, I think i can modify it to take a bunch of cli flags and make it call `parseFlags` to get the cliInput

**Comment by azdagron** [comment]
Ah..... ok, the problem was that the CLI had the default on it, so it was always set, and therefore took precedence over the other.

**Comment by lumjjb** [comment]
ok tests should be updated now

**Review by azdagron — APPROVED** [review]
Thanks for fixing this up, @lumjjb!

**Pull request merged**
