### PR TITLE
Don't run CI for PRs that contain only doc changes

### PR DESCRIPTION
**Pull request by rturner3**
Running the build/test steps for doc-only changes is unnecessary,
time-consuming, and adds to the overall cost of maintaining the project.
Don't run CI for PRs that only contain .md changes or changes within the
`doc` directory.

### CODE REVIEW

**Comment by azdagron** [comment]
In theory, I'm all on board for this kind of change. In practice however, I'm not sure how PRs targeting only documentation would pass the status checks we require on the protected branches (since those status checks wouldn't run). Since they don't run, are we ok? or will we require an "admin" merge to merge these kinds of PRs to bypass the status check requirement?

**Comment by rturner3** [comment]
That's a great question - I'm actually not sure how GitHub will handle the status checks if the PR doesn't trigger the CI build for doc-only PRs. I suppose an admin merge could always be done, but that does potentially open up a can of worms to use that as part of a regular merge process.

One option is to merge this, try to open a doc-only PR as a test, and then revert this change if the PR fails the status checks. Otherwise, I think I can only speculate what might happen. WDYT @azdagron ?

**Comment by azdagron** [comment]
Heh, sure, let's give that a shot.

**Comment by rturner3** [comment]
Ironic that CI failed on this PR :)

**Pull request merged**
