### PR TITLE
oidc-discovery-provider support expose the serivce on https

### PR DESCRIPTION
**Pull request by itomsawyer**
**Pull Request check list**

- [ *] Commit conforms to CONTRIBUTING.md?
- [ *] Proper tests/regressions included?
- [ *] Documentation updated?

**Affected functionality**
oidc-discovery-provider can expose the service on https. The service use certificates minted by ServerAPI to serve TLS connections.

**Description of change**
Add a new configuration option listen_tls_addr.
When  listen_tls_addr, use a x509svid to subscribe the minted x509 SVID and use the certificates in x509 SVID to serve TLS requests.

**Which issue this PR fixes**

**Quickstart example**

Start a local Spire server

```
./bin/spire-server run -config conf/server/server.conf
```

Start a local OIDC-provider to connect with Spire server and expose OIDC service.

```
./bin/oidc-discovery-provider  -config conf/server/oidc-provider.conf
```

Access the  OIDC service locally.
``` 
curl https://localhost:8188/.well-known/openid-configuration --cacert ./conf/server/dummy_upstream_ca.crt 
```

``` json
{
  "issuer": "https://localhost:8188",
  "jwks_uri": "https://localhost:8188/keys",
  "authorization_endpoint": "",
  "response_types_supported": [
    "id_token"
  ],
  "subject_types_supported": [],
  "id_token_signing_alg_values_supported": [
    "RS256",
    "ES256",
    "ES384"
  ]
}
```

### CODE REVIEW

**Comment by itomsawyer** [comment]
Hi @azdagron ,  Lots of use cases for me need this feature to be done, I would like to explain a most typical one:

Integrate Spire with K8S.  Workload (act as k8s operator) use spiffe x509 SVID to access k8s resources via apiserver.

More details can be seen from my gist:  https://gist.github.com/itomsawyer/95897af1145a72ccfe333c13e301438f

> Here's some changes of most of spire-tutorial examples:
> 
> * nginx-ingress is needed for tls-termination and provide HTTPS service with self-generated certificates. Because the spire OIDC provider in  [oidc-vault](https://spiffe.io/docs/latest/keyless/vault/readme/) is require ACME to get a let's enrypt certificate which require public internet and DNS record management ability.
> * SPIRE odic-discovery-provider listen on a insecure HTTP socket for serving with nginx-ingress provider HTTPS connections for apiserver.

All of above workaround is due to:
1. k8s apiserver require to access a OIDC serving on HTTPS.
2. k8s cluster is an internal cluster
3. Spire OIDC provider cannot serving on HTTPS without public internet access.

**Comment by azdagron** [comment]
Ok, thanks for that context @itomsawyer. We're discussing this internally and will leave some feedback or do some follow-up hopefully soon.

**Comment by kfox1111** [comment]
This could work with setups where you have an Upstream CA of Spire. Workloads that talk to the discovery-provider will already have that Upstream CA loaded, so will trust a Spire issued cert when talking to the discovery-provider. For example, Keycloak -> discovery-provider

**Comment by kfox1111** [comment]
Though for scalability, maybe we'd want it to use the workload api rather then the server api?

**Comment by rturner3** [comment]
Hey @itomsawyer just a heads up, this is on our plate to look at, but with end of year, we probably won't have a chance to review it in earnest until January 2024.

**Comment by itomsawyer** [comment]
> Though for scalability, maybe we'd want it to use the workload api rather then the server api?

For scalability and decouple from Spire server，workload api is more reasonable. 

If we consider oidc-discovery-provider as a exec-proc extension as spire-controller-manager, server api is more reasonable.

The two ways to fetch SVID for oidc-discovery-provider sounds fine to me. Maybe we can implement both. 
Any further ideas?

**Comment by rturner3** [comment]
Hi @itomsawyer, I apologize for the long delay here. I think the idea to use an X.509-SVID issued by SPIRE Server as the server TLS certificate for the oidc-discovery-provider conceptually makes sense for some use cases.

One initial observation I would offer is that the configuration of oidc-discovery-provider is starting to become fairly complex now, with a lot of options for how to source/provide the bundle material and server certificate. Users now need to piece together various combinations of required configurations in order to set up the oidc-discovery-provider. While this PR adds useful functionality, I think we should be bit mindful of how it impacts overall user experience.

I haven't had a chance to put forth a concrete suggestion on how we can think about structuring/restructuring the config yet, but I'm open to any ideas you might have on this @itomsawyer.

**Comment by evan2645** [comment]
@itomsawyer do you have any ideas on how to address the feedback from @rturner3? It will be a little while before we're able to propose a solution, so help from your side would be great. Please do let us know if this is still of interest, and thanks again for your time

**Comment by rturner3** [comment]
Hey @itomsawyer, I'm going to close this for now since there are some more details that I think need to be worked out about configuration shape and guidance to users about when it would be advisable to use this mode. I think we are happy to take a change like this if we can work out those details.

I would suggest creating an issue where we can discuss this a bit further, and we can take it from there. Thanks!

**Pull request closed without merging**
