### PR TITLE
Thales cipher trust kms plugin

### PR DESCRIPTION
**Pull request by remythales**
**Pull Request check list**

- [X] Commit conforms to CONTRIBUTING.md?
- [X] Proper tests/regressions included?
- [X] Documentation updated?

**Affected functionality**
Key Manager (new)

**Description of change**
Added Built-In plugin to support Thales CipherTrsut KMS

**Which issue this PR fixes**
None

### CODE REVIEW

**Comment by remythales** [comment]
Hi Evan,
I have an a project with HPE Greenlake and we had a request to integrate with Thales Key Manager system.
Do let me know if you have any concerns.

Thanks a lot for your time 
Remy

**Comment by remythales** [comment]
Just to add some info here: The plugin can be used in the free community version of SPIRE. This is to extend the SPIRE feature and non-commercial.

**Comment by evan2645** [comment]
Hi @remythales , very sorry for the delay here, thanks for your patience.

As I mentioned briefly on Slack last week, we need some help formalizing a policy around if/how the project can accept plugins for non-free commercial software/platforms/vendors. There are a few challenges to figure out there, and we've captured them [in this issue](https://github.com/spiffe/spire/issues/4163). IMO, it is beneficial for the project to have such plugins available out-of-the-box, however we need to make sure that we do it in a sustainable way.

In a [past PR](https://github.com/spiffe/spire/pull/4162), the one which triggered the creation of this issue, the author published the plugins on their own as out-of-tree plugins. The reality is, it would be helpful to have an interested vendor participating in the conversation on #4163 so we can arrive at a solution that makes sense to both parties. Please have a look and let us know what you think ... I'm afraid it will be difficult for us to accept these patches without some decisions there first

**Comment by evan2645** [comment]
Hi @remythales, happy new year 😁 

We are planning to close this PR next week if we don't have a path forward. Happy to provide some examples of how to host and ship out-of-tree plugins for SPIRE if that's helpful in the interim

**Comment by remythales** [comment]
Thanks :) Happy New Year to you, too.
The team was on holiday and will be back shortly. I will post any news once I hear back from them.
Thanks for your understanding.

**Comment by remythales** [comment]
Hi Evan,

We do have the integrated test inside the plugin, and we can provide you with the names of the maintainers. I am waiting for new credentials for you to run the integration test suite.

Thanks

**Comment by remythales** [comment]
Hi Evan,

Sorry for not getting back to you sooner, but I managed to pull off some info for you to complete the request.

Here is the first name for the plugin: Anurag JAIN -  anurag.jain@thalesgroup.com
I'm looking for another name to give you; we could move forward this way._

The test suite has already been developed as part of the plugin testing, but it needs the KMS, as I describe below.

There is a community edition option available here - [community version]( https://cpl.thalesgroup.com/encryption/ciphertrust-platform-community-edition)
You can run locally on virtualbox or vsphere or even from cloud marketplaces.
A couple of videos to setup Ciphertrust Manager:
[Locally ]( https://www.youtube.com/watch?v=MNFgVhgMLB4&list=PLw3mEF7reqIN7TKqwUoCTM9dkFA9xer_0&index=7)
[Cloud ]( https://www.youtube.com/watch?v=2TcaAjfqaEE&list=PLw3mEF7reqIM6TdatdDSd5G_tvsNVqNhx)

The capabilities like key management are available for free forever (What we use in the plugin), and there is a 90-day evaluation option (For advanced features that we don't use in the plugin) that can be enabled from CM GUI.

For key management, you may also use the 30-day free trial of  [CipherTrust as a Service](https://cpl.thalesgroup.com/encryption/data-security-platform/ciphertrust-encryption-key-management-service#start)

Thanks,
Remy

**Comment by remythales** [comment]
Excellent, I have contacted the concerned party to have their github handle to me.
Please allow me some time, I will be reaching back as soon as I have the info.

Yes, you are right, the plugin only your the free feature of the CipherTrust Manager KMS.

Thanks for your time.

**Comment by evan2645** [comment]
Ok thank you @remythales! And just to highlight this, the current PR will need to be updated to include the integration test before we can review it 🙏

**Comment by remythales** [comment]
My colleague's GitHub handles is @anugram the associated email is anurag.jain@thalesgroup.com.
The integration test is already part of the PR: pkg/server/plugin/keymanager/ciphertrustkms/ciphertrustkms_test.go

For the second name needed, you can use mine @remythales 

As for now, I would need to move to other hot customer topics, no further development will be done on my side for this PR request. So that we can proceed to close  this subject.

Thanks a lot of your help and patience.

**Comment by evan2645** [comment]
> My colleague's GitHub handles is @anugram the associated email is [anurag.jain@thalesgroup.com](mailto:anurag.jain@thalesgroup.com).
> For the second name needed, you can use mine @remythales

Ok great! Thank you 🙏 

> The integration test is already part of the PR: pkg/server/plugin/keymanager/ciphertrustkms/ciphertrustkms_test.go

These tests are great and we should definitely keep them, but I am talking about functional integration testing using the test suite I linked earlier: https://github.com/spiffe/spire/tree/main/test/integration

A test there for this plugin would be able to fetch the community edition of the kms software, load it against a built and running SPIRE Server, and exercise the various pathways to ensure that everything works as expected.

> As for now, I would need to move to other hot customer topics, no further development will be done on my side for this PR request. So that we can proceed to close this subject.

I'm sorry to hear that, but totally understand. I think this is a good time to highlight the ongoing nature of maintaining upstream source code - there's a general expectation of timely response (especially for security related issues), and so I would hope that your leadership is able to make this time for you and @anugram to support the contribution on an ongoing basis. I previously mentioned that it would be good to jump on a quick zoom call when the time is right, and this is one of the topics I was hoping to discuss at that time.

As for this PR, my sense is that we need a functional integration test as part of this PR in order to feel comfortable taking the contribution. I realize that it's a non-trivial amount of work. I hope you're able to find support for completing it, as well as making the necessary time to maintain the plugin in the long run (though I expect that commitment would be minimal).

Please let me know if it's something you think you'll be able to complete in the next few weeks. Otherwise, I can close this PR out for now and we can re-visit when you have more cycles. Thanks for understanding

**Comment by remythales** [comment]
excellent, 

I will tackle the integration test (Functional) next week. I will do my best to give you access to a public instance of Ciphertrust Manager KMS. So that you don't need to install it on the premises.

I will get to the bottom of this; thanks a lot for your insight and patience.

**Comment by amartinezfayo** [comment]
Hi @remythales, I think that it would be good to have a call about this contribution, so we can align on the needs and expectations. Could you please share your preferred e-mail address and some options that would work for you/your team to have a Zoom call? Thanks!

**Comment by remythales** [comment]
Sure, here is my Thales email.
remy.saksik@thalesgroup.com 

thanks

**Comment by remythales** [comment]
Hi @evan2645,

I have pushed the integration testing.
After discussing with the SPIRE team today and the CipherTrust Thales team, I realized that having CipherTrust Key Manager into a docker for CI/CD is not possible.

I understand the Spire team doesn't want to have external API calls, but it is a faster and easier way of testing. Nevertheless, one option would be to deploy an instance of CipherTrust Key Manager in a Virtual Box [CipherTrust Local VM installation](https://www.youtube.com/watch?v=MNFgVhgMLB4&list=PLw3mEF7reqIN7TKqwUoCTM9dkFA9xer_0&index=7).

It works fine, and the integration testing was successful, the configuration of the plugin is now with a local IP address.

looking forward to hearing from you.
Remy

**Comment by remythales** [comment]
Understood.

Do you have some document on how (pragmatically) to create an external plugin for a key manager?
Please share with me all the material to get started. Not just the configuration of a plugin. What is the role of cmd?
thanks.

**Comment by amartinezfayo** [comment]
Changes in the catalog are not needed, all the changes are self-contained in the external plugin code. No changes in SPIRE will be required.
To author an external plugin, the only difference is that you provide a main function that invokes the `pluginmain.Serve` function. The spire-plugin-sdk repository has a template demonstrating this as part of the KeyManager plugin template: https://github.com/spiffe/spire-plugin-sdk/blob/main/templates/server/keymanager/keymanager.go

Then, you build the plugin code to have a binary that you can reference in the `plugin_cmd` setting. Just make sure that you have a `main` package with the `main` function so you can compile the plugin having the resulting object binary that you set in `plugin_cmd`.

```
    KeyManager "ciphertrust_kms" {
        plugin_cmd = "path/to/ciphertrust_kms"
        #  plugin_checksum = "An optional sha256 of the plugin binary"
        plugin_data = {
            # Plugin settings
        }
    }
```

**Comment by amartinezfayo** [comment]
Since this will be published as an external plugin, I'll go ahead and close this PR. Please reach out if you need any help.

**Pull request closed without merging**
