### PR TITLE
Remove deprecated -ttl flag from spire server cli

### PR DESCRIPTION
**Pull request by heymarcel**
This commit removes the deprecated `-ttl` flag from `spire entry create` and `spire entry update`. 
See discussion in [issue #5254.](https://github.com/spiffe/spire/issues/5254)

**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [x] Proper tests/regressions included?
- [x] Documentation updated?

**Affected functionality**
This commit removes the deprecated `-ttl` flag from `spire entry create` and `spire entry update`. 

**Description of change**
As per the issue referenced above:
> The CLI has long since deprecated the -ttl flag in favor of the SVID specific flags -x509SVIDTTL and -jwtSVIDTTL. The deprecated flag should be removed.

**Which issue this PR fixes**
fixes#5254

### CODE REVIEW

**Review by azdagron — DISMISSED** [review]
LGTM! Thanks, @heymarcel !

**Comment by MarcosDY** [comment]
can you update ITs that are using -ttl and replace that with x509ttl or jwtttl depending the case?

**Comment by heymarcel** [comment]
@MarcosDY Sorry about missing the integration tests. I have them working now, but I notice the Windows unit tests are still failing. Is that expected, or am I missing something? https://github.com/heymarcel/spire/actions/runs/10815947896/job/30006064864

**Comment by MarcosDY** [comment]
Thanks for taking care of this!
Yes, you'll need to update the expected messages for Windows [here](https://github.com/spiffe/spire/blob/main/cmd/spire-server/cli/entry/util_windows_test.go#L5)

**Comment by heymarcel** [comment]
Thanks! I've got that running now as well.

**Review by MarcosDY — APPROVED** [review]

**Pull request merged**
