### PR TITLE
Add windows build to ci

### PR DESCRIPTION
**Pull request by MarcosDY**
Add Jobs to:
- Build Artifact
- Run Tests
- Run Lint

On windows

### CODE REVIEW

**Comment by amartinezfayo** [comment]
Thanks @MarcosDY, this is great!
To avoid any ambiguity, it will probably good to have the id/name of Linux jobs updated to specify that they are on Linux. E.g. `cache-deps (linux)`

**Review by amartinezfayo — APPROVED** [review]
Thank you @MarcosDY!

**Comment by azdagron** [comment]
On concern, is that I think this is adding the windows binaries into the `binaries` artifact? will this end up publishing them? are we ready for that?

**Comment by amartinezfayo** [comment]
> On concern, is that I think this is adding the windows binaries into the binaries artifact? will this end up publishing them? are we ready for that?

Thanks for pointing that @azdagron. My understanding is that the [Release Build workflow](https://github.com/spiffe/spire/blob/main/.github/workflows/release_build.yaml) is the one that publishes the artifacts for a release, and the changes only affect the PR builds. I'm not sure if having the artifacts in the PR builds may cause confusions? Maybe we can refrain from adding them until we have a Windows build that is really usable.

**Comment by azdagron** [comment]
@MarcosDY and I chatted offline and he pointed this out. I think we're ok with it as-is :) Sorry for the confusion.

**Pull request merged**
