### PR TITLE
Add Roadmap.md file 

### PR DESCRIPTION
**Pull request by anjaltelang**
This commit adds the Roadmap.md file to the main branch.
This will help the contributors to update the roadmap items
since spire.wiki is not editable by all.

Signed-off-by: Anjali Telang <atelang@vmware.com>

**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [n/a] Proper tests/regressions included?
- [x] Documentation updated?

**Affected functionality**

N/A

**Description of change**

This commit adds the Roadmap.md file to the main branch.
This will help the contributors to update the roadmap items
since spire.wiki is not editable by all.

**Which issue this PR fixes**

N/A

### CODE REVIEW

**Comment by azdagron** [comment]
This is great, @anjaltelang ! This will make it much easier to receive contributions to the Wiki. I'm good with this, though as @amartinezfayo mentioned, we should probably update the link in the README.md to point to this new location.

**Comment by anjaltelang** [comment]
Thanks @azdagron and @amartinezfayo ! I have updated the README.md to reflect the new link.

**Review by amartinezfayo — APPROVED** [review]
Thank you for this @anjaltelang!

**Comment by azdagron** [comment]
This looks great, @anjaltelang :) I reviewed the latest commit with the updated hyperlink in README.md and just now noticed that the name of the file is `Roadmap.md`. Our naming conventions for top-level markdown files is UPPERCASE.md.

I apologize for the extra round of changes, but would you mind renaming it to `ROADMAP.md` (and updating the link in README.md)?

**Pull request merged**
