### PR TITLE
Update plugin_agent_workloadattestor_docker.md

### PR DESCRIPTION
**Pull request by raissonsouto**
**Affected functionality**
None.

**Description of change**
Improving documentation of the Docker workload attestor.

### CODE REVIEW

**Review by amartinezfayo — COMMENTED** [review]
Thank you @raissonsouto for this.
There may be a confusion here. The `docker:image_id` selector should generate a selector that is a digest. It's a computed (truncated) SHA256 hash of the image configuration object. It shouldn't be the REPOSITORY:TAG.
Have you seen this selector to be something different than a digest?

**Comment by raissonsouto** [comment]
This documentation is based in my experience with SPIRE.

I was using a Envoy proxy within docker and using a SPIRE agent in the host machine with the docker workload attestator and when I tried to use the selector `docker:image_id` using the hash of the Envoy image, it fails to get the SVID. However, I discover that using the `image_name:version` worked.

If you want to try yourself, these are the files used:

server.conf

```
server {
    bind_address = "127.0.0.1"
    bind_port = "8081"
    trust_domain = "example.org"
    data_dir = "./data/server"
    log_level = "DEBUG"
    ca_ttl = "240h"
    default_x509_svid_ttl = "120h"
    ca_key_type = "rsa-4096"

    ca_subject {
        country = ["BR"]
        organization = ["SmartCampus"]
    }
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "sqlite3"
            connection_string = "./data/server/datastore.sqlite3"
        }
    }

    NodeAttestor "join_token" {
        plugin_data {
        }
    }

    KeyManager "memory" {
        plugin_data = {}
    }
}
```

agent.conf
```
agent {
    data_dir = "./data/agent"
    log_level = "DEBUG"
    server_address = "127.0.0.1"
    server_port = "8081"
    trust_domain = "example.org"
    insecure_bootstrap = true
    workload_x509_svid_key_type = "rsa-2048"
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }
    
    KeyManager "disk" {
        plugin_data {
            directory = "./data/agent"
        }
    }
    
    WorkloadAttestor "docker" {
        plugin_data {}
    }
}
```

compose.yaml:
```
version: '3'

services:

  envoy:
    container_name: envoy
    image: envoyproxy/envoy:contrib-v1.29.1
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - /tmp/spire-agent/public:/tmp/spire-agent/public
    ports:
      - "10000:10000"
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "-l", "debug"]

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
```

envoy.yaml
```
node:
  id: default
  cluster: server
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          common_http_protocol_options:
            idle_timeout: 1s
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: "/dev/stdout"
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          require_client_certificate: true
          common_tls_context:
            tls_certificate_sds_secret_configs:
            - name: spiffe://example.org/envoy
              sds_config:
                resource_api_version: V3
                api_config_source:
                  api_type: GRPC
                  transport_api_version: V3 
                  grpc_services:
                    envoy_grpc:
                      cluster_name: spire_agent
            validation_context_sds_secret_config: 
              name: "spiffe://example.org"
              sds_config:
                resource_api_version: V3
                api_config_source:
                  api_type: GRPC
                  transport_api_version: V3
                  grpc_services:
                    envoy_grpc:
                      cluster_name: spire_agent

  clusters:
  - name: service
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    load_assignment:
      cluster_name: service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080
  - name: spire_agent
    connect_timeout: 0.25s
    http2_protocol_options: {}
    load_assignment:
      cluster_name: spire_agent
      endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                pipe:
                  path: /tmp/spire-agent/public/api.sock

```
### Steps
1. Deploy SPIRE server in the host machine
2. Generate the join token for spiffe://example.org/agent
3. Deploy SPIRE agent in the host machine
4. Create a entry for Envoy:
```
sipre-server entry create -parentID spiffe://example.org/agent -spiffeID spiffe://example.org/envoy -selector docker:image_id:644f45f6626c
```

5. See SPIRE agent logs failing to send the SVID
```
DEBU[0114] Received StreamSecrets request                method=StreamSecrets nonce= pid=14066 resource_names="[spiffe://example.org/envoy]" service=S
DS.v3 subsystem_name=endpoints version_info=                                                                                                          
ERRO[0114] Error building stream secrets response        error="rpc error: code = InvalidArgument desc = workload is not authorized for the requested 
identities [\"spiffe://example.org/envoy\"]" method=StreamSecrets pid=14066 service=SDS.v3 subsystem_name=endpoints 
```

6. Now, make the new entry:
```
spire-sserver entry create -parentID spiffe://example.org/agent -spiffeID spiffe://example.org/envoy -selector docker:image_id:envoyproxy/envoy:contrib-v1.29.1
```

7. Finally, check the SPIRE agent logs:
```
DEBU[0185] Received StreamSecrets request                method=StreamSecrets nonce=31ec6044 pid=14066 resource_names="[spiffe://example.org]" service
=SDS.v3 subsystem_name=endpoints version_info=14                                                                                                      
DEBU[0185] SVID updated                                  entry=02654974-eca8-4223-baef-cdee7eb49d85 spiffe_id="spiffe://example.org/envoy" subsystem_n
ame=cache_manager                                                                                                                                     
DEBU[0185] Sending StreamSecrets response                count=1 method=StreamSecrets nonce=584cfac6 pid=14066 service=SDS.v3 subsystem_name=endpoints
 version_info=15      
```

**Comment by amartinezfayo** [comment]
Thank you @raissonsouto. Could you share SPIRE Agent logs when the attestation happens? Particularly, the DEBUG log message `PID attested to have selectors`, that should expose the discovered selectors.

**Comment by raissonsouto** [comment]
Another useful information, I'm using SPIRE 1.9.1

**Review by amartinezfayo — COMMENTED** [review]
Thank you @raissonsouto for bringing this up. I was able to reproduce the same kind of output for the `image_id` selector, indicating the image name. I filed #5114 to address having a selector name that is misleading.

I think that we should probably update the "Workload Selectors" table as well, with a value for `image_id` more like an image name instead of a digest, and also the description.
There are a couple of changes that we should also make to make the linter happy.
Thank you very much for this contribution!

**Comment by raissonsouto** [comment]
Hello @amartinezfayo, 

I apologize for the delay in implementing the required fixes, I've been immersed in my bachelor's thesis (which is about access control of Kafka using SPIRE!!).

**Comment by amartinezfayo** [comment]
@raissonsouto No worries!
DCO is missing, could you please fix that so we can merge this?

**Comment by amartinezfayo** [comment]
Hi @raissonsouto, quick reminder that we need to have DCO fixed to be able to merge this contribution.

**Comment by amartinezfayo** [comment]
@raissonsouto Since we still have the DCO missing in this PR, I've opened #5220 taking this contribution so we can get it merged. I'm closing this PR in favor of #5220. Thanks again!

**Pull request closed without merging**
