### PR TITLE
Flip default 'upstream_bundle' value to true

### LINKED ISSUE #1189: Flip default value of upstream_bundle to true
Following through on #1095, flip the default value of the upstream_bundle configurable to true now that a warning has been put in place.

Blocked on 0.10.0-dev

### PR DESCRIPTION
**Pull request by marcosy**
**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [x] Proper tests/regressions included?
- [x] Documentation updated?

**Affected functionality**
SPIRE server default configuration values

**Description of change**
This PR flips the `upstream_bundle` configurable default value to `true`.

**Which issue this PR fixes**

Fixes #1189

### CODE REVIEW

**Comment by marcosy** [comment]
> Also, I think we need to extend the checks in run.go to also handle when UpstreamAuthority is being used

will fix!

> I think we can also introduce the warning if an UpstreamCA is configured with an explicit upstream_bundle=false at the same time.

Just to check, do you suggest deprecating the configurable now? or to only add a warning when it is set to `false` (explaining that it will be deprecated in a future release)?

I was thinking that perhaps deprecating and changing the default value for the configurable in a single step may be a bit confusing... or maybe not.

**Comment by azdagron** [comment]
I'm not suggesting we deprecate it now (as in remove it). But thinking about it some more I think we should do the following:

For those who:
1) have no `upstream_bundle` configurable set - they need to continue to be warned that `upstream_bundle` defaults to true now (as you have already in this PR)
2) have `upstream_bundle = false` - they should be warned that we are deprecating `upstream_bundle` in a future release so they can start to migrate away. I don't see a reason to push this off another release.
3) have `upstream_bundle = true` - they should not get any warning that `upstream_bundle` will be deprecated since if they remove `upstream_bundle` they will start getting the warning from \#1.

After this next release, we can open up a PR that:
1) For those without `upstream_bundle` configured - now issues no warning
2) For those with `upstream_bundle = false` - fail to configure (since we've given them a release to migrate)
3) For those with `upstream_bundle = true` - warn that `upstream_bundle` is being removed and they
should remove it from their config.

Does that smell right @evan2645 ?

**Comment by evan2645** [comment]
>have no upstream_bundle configurable set - they need to continue to be warned that upstream_bundle defaults to true now (as you have already in this PR)

I don't think we need to continue warning afterwards, do we? We have been warning for one full release, and if I want to just take advantage of the default behavior, the warning feels superfluous

>have upstream_bundle = true - they should not get any warning that upstream_bundle will be deprecated since if they remove upstream_bundle they will start getting the warning from #1.

This feels like a good supporting point for the above comment. We want to fully deprecate `upstream_bundle` which means that, when we do, we will bail out with unknown config option... so, I think we need to start warning here in 0.10 even if it's set to true because that will not be a good config in 0.11

I feel like the clearest way to communicate the logic is through a table. I took a shot at what I feel like the behavior here should be, and along the way had a couple insights. Here is a table representing my understanding of the current state (i.e. not considering the change in this PR):

|                           | upstream_bundle true | upstream_bundle false | upstream_bundle not set |
|---------------------------|:--------------------:|:---------------------:|:-----------------------:|
| **Upstream Present**     | Do nothing           | Do nothing            | Warn (new default)      |
| **Upstream Not Present** | Do nothing           | Do nothing            | Do nothing              |

The next step, and what I _think_ this PR should do, ended up looking like this:

|                           | upstream_bundle true | upstream_bundle false | upstream_bundle not set |
|---------------------------|:--------------------:|:---------------------:|:-----------------------:|
| **Upstream Present**     | Warn (deprecating)   | Warn (deprecating)    | Do nothing              |
| **Upstream Not Present** | Warn (deprecating)   | Warn (deprecating)    | Do nothing              |

And then the final step, which should not occur until 0.11.0, looks like this (the final state):

|                           | upstream_bundle true | upstream_bundle false | upstream_bundle not set |
|---------------------------|:--------------------:|:---------------------:|:-----------------------:|
| **Upstream Present**     | Fatal                | Fatal                 | Do nothing              |
| **Upstream Not Present** | Fatal                | Fatal                 | Do nothing              |

With the tables, what  became clear to me is that we probably want to warn _any time_ that upstream_bundle is set, because it will not pass validation in 0.11 (when we also flip unknown config detection to be fatal). We have already warned when/where appropriate about the default change, so if you are using the default value, no further warning or message should be necessary.

I think the end result is actually a combination of the two phases that @azdagron posted.

Do these tables look and feel correct?

**Comment by azdagron** [comment]
You make a good point that we've been warning that the default was going to change for a full release and that it seems superfluous to continue warning if they are relying on the default.

I'm good with this plan as described in the tables.

**Comment by marcosy** [comment]
Sounds good to me too! I'll update the PR to reflect the scenario of the second table.

**Pull request merged**
