### PR TITLE
Document profiling configurations for Server and Agent

### PR DESCRIPTION
**Pull request by rturner3**
Adds documentation for configuration parameters used to set up a pprof endpoint that have been around for a long time.

The entire config tables got affected because the description for `profiling_endpoint` exceeded the length of any other config parameter description. The table is formatted in the Markdown in a human-friendly manner where all the columns are aligned, which resulted in some noise in the diff to keep that convention consistent.

### CODE REVIEW

**Comment by azdagron** [comment]
Do we also want to add documentation for the profiling_freq and profiling_names configurables? The latter is especially important... I think they are required?

In hindsight, I wish all of these profiling configurables were in their own section...

**Comment by rturner3** [comment]
> Do we also want to add documentation for the profiling_freq and profiling_names configurables? The latter is especially important... I think they are required?
> 
> In hindsight, I wish all of these profiling configurables were in their own section...

Sure, makes sense to document them all. I'll update the PR.

`profiling_freq` and `profiling_names` are not required if you only want to expose the `net/http/pprof` endpoint. Those configurables are used to dump profiling data to files on disk for a given frequency.

**Comment by azdagron** [comment]
Ah, ok.

**Review by azdagron — APPROVED** [review]
Thanks, @rturner3!

**Pull request merged**
