### PR TITLE
Add IBM s390x multi arch support

### PR DESCRIPTION
**Pull request by Basavaraju-G**
This PR will add s390x multi arch support.

Pull Request check list
[x] Commit conforms to CONTRIBUTING.md?

Affected functionality
No existing functionality affected. New Arch support is added

Description of change.
As of now, spire works on amd64 and arm64 platform. This PR will add support for s390x platform.

Signed-off-by: Basavaraju G <basavaraju013@gmail.com>

### CODE REVIEW

**Comment by evan2645** [comment]
Hi @Basavaraju-G!

While this change itself is small, it has bigger maintenance and support implications. ARM support was recently introduced due to growing demand, however along with that was also a lot of conversation and work around how to test/build/ship an ARM flavored SPIRE.

Choosing to support a new architecture is unfortunately not a decision we can easily make .. if there is sufficient demand, and we have a good way to run tests and build artifacts on that platform, then it's certainly something we're open to discussing ... that said, we haven't been asked for s390x before (as far as I know), and we don't see a clear path forward right now for test and build

**Comment by Basavaraju-G** [comment]
Hi @evan2645, thank you for your review.
Yes, Right now we are actively exploring CI part for building and testing spire components on s390x platform. one of the possible idea is to use IBM Public Cloud zVPC machines. For building images we can use existing docker buildx setup to build multi-arch images for s390x. we will come up the better way of building and testing on s390x platform. 

Thanks

**Comment by evan2645** [comment]
> one of the possible idea is to use IBM Public Cloud zVPC machines

Would you be able to provide an account and free credits for the project to test and build on? I think we'd also want someone on the hook to fix the build there if it ever breaks .. the added overhead is expensive for SPIRE maintainers. The project is (in general) willing to accept such overhead if there is substantial community need, but this is the first time we have a request to support this architecture.

I feel that the lowest friction path forward is to maintain a light fork and build + ship this flavor of SPIRE independently

**Comment by olira** [comment]
Hi @evan2645,

In addition to the before mentioned IBM Public Cloud zVPC machines, there is the [IBM LinuxOne Community Cloud](https://linuxone.cloud.marist.edu/) which is intended for development and testing, mainly for OpenSource projects or education. You can register as a project there and once approved should be able to access a Z Linux Virtual Server.

**Comment by evan2645** [comment]
Thanks for pointing that out @olira

We again discussed this PR in the contributor sync call yesterday, and the consensus was that we're happy to take changes to the makefile that support building on s390x without forking the project, but we can't commit to shipping support for s390x in our artifacts until a number of other things are figured out. So, I think there are two paths forward:
* Remove the change to the `PLATFORMS` variable such that SPIRE doesn't ship s390x support in container images, but still supports building on s390x with an unmodified makefile. The variable can then be overridden by env var or command line option in your build system

OR

* Convert this PR to an issue, where we can discuss the possibility of SPIRE officially supporting s390x. Things that we will need to be answered there include a detailed plan for build/test (perhaps using some resources from the community cloud as referenced), a list of folks to be named as long-term maintainers for this platform, and some kind of statement or evidence of significant community need.

**Comment by Basavaraju-G** [comment]
Hi @evan2645 thank for you suggestion. we are okay with first option. i will remove platform changes as suggested.

**Comment by evan2645** [comment]
Thank you @Basavaraju-G , this looks good. Can you please force push this PR with a [DCO set](https://github.com/apps/dco) on the commit(s)? We will merge it as soon as the DCO is signed

**Comment by evan2645** [comment]
Hi again @Basavaraju-G .. we're ready to take this change but need the DCO to be signed off first. Mind force pushing this branch with the DCO set on your commits? You'll need to rewrite them with `git -s` flag set.

https://wiki.linuxfoundation.org/dco

**Comment by Basavaraju-G** [comment]
Hi @evan2645 there is some issue with my git repo. opened new PR here https://github.com/spiffe/spire/pull/4127. closing this one.

**Pull request closed without merging**
