### PR TITLE
agent, server: add option to log source location

### PR DESCRIPTION
**Pull request by c4rlo**
**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [x] Proper tests/regressions included?
- [x] Documentation updated?

**Affected functionality**

Logging in `spire-agent` and `spire-server`.

**Description of change**

Add an option to both agent and server to enable logging of the source location (file name, line number, function name).

The motivation is to make it easier to locate the code that emitted some given log line, especially if that is an error that should be investigated.

This new option is available both via the configuration file and as a command-line flag.

Quick demo:

```
$ bin/spire-agent run | head -3
time="2023-06-08T21:26:08+01:00" level=warning msg="Current umask 0022 is too permissive; setting umask 0027"
time="2023-06-08T21:26:08+01:00" level=info msg="Starting agent with data directory: \"./.data\""
time="2023-06-08T21:26:08+01:00" level=info msg="Plugin loaded" external=false plugin_name=join_token plugin_type=NodeAttestor subsystem_name=catalog

$ bin/spire-agent run -logSourceLocation | head -3
time="2023-06-08T21:26:09+01:00" level=warning msg="Current umask 0022 is too permissive; setting umask 0027" file="umask_posix.go:22" func=github.com/spiffe/spire/pkg/common/cli.SetUmask
time="2023-06-08T21:26:09+01:00" level=info msg="Starting agent with data directory: \"./.data\"" file="agent.go:44" func="github.com/spiffe/spire/pkg/agent.(*Agent).Run"
time="2023-06-08T21:26:09+01:00" level=info msg="Plugin loaded" external=false file="catalog.go:189" func=github.com/spiffe/spire/pkg/common/catalog.Load plugin_name=join_token plugin_type=NodeAttestor subsystem_name=catalog
```

## Discussion

- Note that there is some performance impact. We use the same method as `logrus` (`runtime.Callers`); its docs [mention](https://pkg.go.dev/github.com/sirupsen/logrus#readme-logging-method-name) and overhead of "between 20 and 40%". When I run `logrus`'s `go test -bench=.*CallerTracing`, I get something closer to 100% overhead (i.e., caller reporting roughly doubles the cost of a logging call). In practice, most likely nothing to worry about too much, though it's an extra reason why this is opt-in.
- I chose to log the basename of the source file only, as the fully-qualified function name (with package name) includes enough info on where to find the source file.
- Possible enhancement: allow specifying a log level above which the source location gets included (e.g. only for errors and above). I felt this might not be worth the complexity.
- Possible enhancement: also implement this for oidc-discovery-provider. Happy to do this if there is demand.

### CODE REVIEW

**Comment by edwbuck** [comment]
Per maintainers discussion, there's some question about the utility of such a choice.  I'll be looking to follow up with c4lro to see if we have something to gain that the maintainers are just missing at the moment.

**Comment by c4rlo** [comment]
As mentioned, the motivation is to make it easier to locate the code that emitted some given log line, especially when investigating an error.

Without this, the typical workflow would be to grep the source code for the error message. And error messages are not always unique. A crude way of seeing some of this:

```
$ rg -t go -g '!*_test.go' -or '$1' -I '\blog\.\w+\("([^"]+)"\)' cmd pkg | sort | uniq -c | sort -nr | head -10
      3 SVID updated
      3 Missing required audience parameter
      3 Entry updated
      3 Entry created
      3 Caller is no longer being watched
      2 Stopping Server APIs
      2 Starting Server APIs
      2 Server APIs have stopped
      2 Key enqueued for deletion
      2 Failed to enqueue key for deletion
```

Also, sometimes logged messages cannot be found via grep, for a variety of reasons:

- Log message is created via format specifiers like `%s`; fortunately not much of that is happening in SPIRE, thanks to the use of structured logging to add extra info.
- Log message spans multiple lines in the source code.
- Log message is manipulated in some way before being emitted. For example, the [`api.MakeErr`](https://github.com/spiffe/spire/blob/6f747de0f0dc8636f2275a6e004a2816571b4400/pkg/server/api/status.go#LL39C8-L39C8) function takes some error information as input, potentially changes capitalization, and then logs it. This one is actually what inspired this PR, as a case-sensitive grep I was doing did not return results because of this.

**Comment by edwbuck** [comment]
@c4rlo Thanks for the updates.  I see what you mean.

"SVID Updated" is located in a number of places (pkg/agent/manager/cache/cache.go, pkg/agent/manager/cache/lru_cache.go, and pkg/agent/manager/storecache/cache.go)

In the case of the the cache/lru_cache duplication, it's because these are either / or caching solutions, and one needs to indicate that the SVID was updated no matter what caching solution you use.  

For the storecache it's a bit more insidious.  Both objects are typed as 'Cache' and only the package names differ.  The two caches are caching SVIDs, even if they are holding different information.  To make matters worse, both are in 'cache.go' files (in different packages).

I think this example alone shows that there is some merit to the idea of logging line numbers, even if many of the other messages don't directly benefit, it is more a matter now of discussing among the maintainers if this is the desired approach or if the approach is to update the messages for clarity.

It's also apparent to me after reading the code that most of these are duplicates where one or more "alternative" solutions are present, and the core code was copied (lru_cache for caches that don't hold all values, copied from cache that held all values).  This implies that if logging in the plugin is cut-and-pasted; never an ideal solution for code maintenance.  Perhaps some of these messages could benefit from being pulled as logging item on the "other" side of the plugin, but that assumes operations that are called across the plugin interface, or extending the plugin framework for the kind of plugin to "standardize" messages internally.

I think there is enough information for the maintainers to make a decision, and my role was to explore the submission to see if it had sufficient merit to suffer the loss of performance.  I think the feature is a little bit more than "nice to have", considering my investigation into the message "SVID updated" and if the maintainers don't wish to resolve the confusion with this pull request, I will be opening an Issue to ensure that we either clarify the log location in the source code by a different means, or de-duplicate the messages by pushing them up into modules providing a common framework for multiple alternative implementations.

**Comment by edwbuck** [comment]
Un-assigning myself to complete the hand off to Andrew.  Thanks Andrew for handling this personally.

**Review by azdagron — DISMISSED** [review]
Thanks, @c4rlo !

**Comment by azdagron** [comment]
Looks like we have a linting failure. Can you address that @c4rlo ? If not, let me know and we can push a commit on top.

**Comment by c4rlo** [comment]
> Looks like we have a linting failure. Can you address that @c4rlo ? If not, let me know and we can push a commit on top.

Done. (`goimports` was being weirdly specific about one particular whitespace issue – nothing to do with `imports`, and only in one particular place.)

I've amended the commit and rebased.

**Review by azdagron — APPROVED** [review]
Thanks!

**Pull request merged**
