### PR TITLE
Fix values related to ca_subject of spire-server config examples

### PR DESCRIPTION
**Pull request by ryysud**
**Pull Request check list**

- [x] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

Nothing.

**Description of change**

I found incorrect examples of spire-server config when updating the config related to CA.
So, I fixed it to correct value.

`CommonName` is incorrect, `common_name` is correct.
https://github.com/spiffe/spire/blob/5ef1c258bb27e0abf1ef0235e60e610ac07506e5/cmd/spire-server/cli/run/run.go#L68

**Which issue this PR fixes**

Nothing.

### CODE REVIEW

**Comment by ryysud** [comment]
I have fixed the camel-cased `CommonName` to the correct value according to the document in this time. Please comment if you want the camel-cased `Country` and` Organization` to follow the documentation as well as `common_name` .
https://github.com/spiffe/spire/blob/2942beeaa8ecf17837c2d7c02025aa47864156b9/doc/spire_server.md#server-configuration-file

**Comment by evan2645** [comment]
@ryysud thank you for this! Yes, correcting `country` and `organization` while we're at it would be great, especially since it will be consistent with the updated `common_name`.

**Comment by ryysud** [comment]
@evan2645 ok. I fixed it with https://github.com/spiffe/spire/pull/941/commits/6084949ffb4d18fbe25919ce298a9f52910ab6cf .

**Comment by ryysud** [comment]
Thank you for your review!

**Pull request merged**
